(function(){
  'use strict';
  var files=[
    ['Bioquímica II','21 ago. 2026','Actividades 3 y 4 · DOCX','assets/class-hub/biochemistry/2026-08-21/actividades-3-y-4-bioquimica-ii.docx'],
    ['Bioquímica II','21 ago. 2026','Pizarra · déficit de insulina','assets/class-hub/biochemistry/2026-08-21/board/01-deficit-insulina.svg'],
    ['Bioquímica II','21 ago. 2026','Pizarra · cetogénesis y acidosis','assets/class-hub/biochemistry/2026-08-21/board/02-cetogenesis-acidosis.svg'],
    ['Bioquímica II','21 ago. 2026','Pizarra · cerebro y osmoles','assets/class-hub/biochemistry/2026-08-21/board/03-cerebro-osmoles.svg'],
    ['Bioquímica II','19 ago. 2026','Pizarra · complejo PDH','assets/class-hub/biochemistry/2026-08-19/board/01-pdh-cofactores.svg'],
    ['Bioquímica II','19 ago. 2026','Pizarra · regulación glucolítica','assets/class-hub/biochemistry/2026-08-19/board/02-regulacion-glucolisis.svg'],
    ['Epidemiología','19 ago. 2026','Organización Urg y Emergencias · PPTX','assets/class-hub/epidemiology/2026-08-19/organizacion-urgencias-emergencias.pptx'],
    ['Epidemiología','19 ago. 2026','Trabajo práctico · DOCX','assets/class-hub/epidemiology/2026-08-19/trabajo-practico-salud-publica-epidemiologia.docx'],
    ['Epidemiología','Bloque anterior','Atención Primaria de la Salud · PPTX','assets/class-hub/epidemiology/2026-08-16/atencion-primaria-salud.pptx'],
    ['Epidemiología','Bloque anterior','Manual RAC Paraguay · PDF','assets/class-hub/epidemiology/2026-08-16/manual-rac-paraguay-2011.pdf'],
    ['Epidemiología','Bloque anterior','Salud Pública Paraguay · PDF','assets/class-hub/epidemiology/2026-08-16/salud-publica-paraguay.pdf'],
    ['Fisiología II','20 ago. 2026','Ejercicios de fijación del sistema nervioso · PDF','assets/class-hub/physiology/2026-08-20/ejercicios-fijacion-sistema-nervioso.pdf'],
    ['Fisiología II','24 ago. 2026','Sensibilidades somáticas · PDF','assets/class-hub/physiology/2026-08-24/sensibilidades-somaticas.pdf'],
    ['Fisiología II','24 ago. 2026','Ejercicios · sensibilidades somáticas · PDF','assets/class-hub/physiology/2026-08-24/ejercicios-sensibilidades-somaticas.pdf'],
    ['Fisiología II','24 ago. 2026','Participación activa 24-08 · PDF','assets/class-hub/physiology/2026-08-24/participacion-activa-24-08.pdf'],
    ['Fisiología II','24 ago. 2026','Repaso · sinapsis y receptores · PDF','assets/class-hub/physiology/2026-08-24/repaso-sinapsis-receptores.pdf'],
    ['Fisiología II','17 ago. 2026','Organización, sinapsis y receptores · PDF','assets/class-hub/physiology/2026-08-17/organizacion-sinapsis-receptores.pdf'],
    ['Microbiología II · Teórica','24 ago. 2026','Casos clínicos y candidiasis · PDF optimizado','assets/class-hub/microbiology-theory/2026-08-24/expanded-cases/casos-clinicos-y-candidiasis-24-08.pdf'],
    ['Microbiología II · Teórica','10 ago. 2026','Micología · generalidades · PDF','assets/class-hub/microbiology-theory/2026-08-10/micologia-generalidades.pdf'],
    ['Microbiología II · Teórica','10 ago. 2026','Micosis superficiales · PDF','assets/class-hub/microbiology-theory/2026-08-10/micosis-superficiales.pdf'],
    ['Nutrición','Seminario','Instrucciones para presentación oral · DOCX','assets/class-hub/instructivo-presentacion-oral-semana-3.docx'],
    ['Nutrición','Seminario','Ejemplo de primera página · DOCX','assets/class-hub/modelo-portada-seminario-nutricion.docx']
  ];
  function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function normalizedCourse(value){var text=String(value||'').toLowerCase();if(text.normalize)text=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'');return text.replace(/[^a-z0-9]+/g,' ').trim();}
  function courseKey(value){var course=normalizedCourse(value);if(course.indexOf('microbiologia')>=0){if(course.indexOf('pract')>=0)return'microbiologia-practica';if(course.indexOf('teor')>=0)return'microbiologia-teorica';}if(course.indexOf('bioquim')>=0)return'bioquimica';if(course.indexOf('epidemi')>=0||course.indexOf('salud publica')>=0)return'epidemiologia';if(course.indexOf('fisiolog')>=0)return'fisiologia';if(course.indexOf('nutric')>=0)return'nutricion';return course.replace(/ /g,'-');}
  function requestedCourse(){try{return courseKey(new URLSearchParams(window.location.search).get('course')||'');}catch(error){return'';}}
  function fileTypeFrom(url,title){var match=String(url||'').split('?')[0].match(/\.([a-z0-9]+)$/i);if(match)return match[1].toUpperCase();var titleMatch=String(title||'').match(/\b(PDF|PPTX|DOCX|SVG|JPG|JPEG|PNG)\b/i);return titleMatch?titleMatch[1].toUpperCase():'ARCHIVO';}
  function canonicalFileUrl(value){try{var parsed=new URL(value,window.location.href),host=parsed.hostname.toLowerCase();if(host==='drive.google.com'||host==='docs.google.com'){var driveId=parsed.searchParams.get('id'),pathMatch=parsed.pathname.match(/\/d\/([^/]+)/);if(!driveId&&pathMatch)driveId=pathMatch[1];if(driveId)return'drive:'+driveId;}parsed.hash='';return parsed.href;}catch(error){return String(value||'').trim();}}
  function activeFile(file){return Boolean(file)&&(file.removedAt===null||file.removedAt===undefined||String(file.removedAt).trim()==='');}
  function normalizedManagedFile(file){var record=Object.assign({},file||{});record.id=String(record.id||'').trim();record.course=String(record.course||'').trim();record.title=String(record.title||'').trim();record.url=String(record.url||'').trim();record.fileType=String(record.fileType||fileTypeFrom(record.url,record.title)).trim().toUpperCase();record.createdAt=String(record.createdAt||'').trim();record.modifiedAt=String(record.modifiedAt||'').trim();record.firstSeenAt=String(record.firstSeenAt||'').trim();record.visibility=String(record.visibility||'').trim();record.lessonDate=String(record.lessonDate||'').trim();record.managed=true;return record;}
  function mergeManagedFiles(catalogFiles,apiFiles){var verifiedCatalog=(catalogFiles||[]).filter(function(raw){return raw&&String(raw.visibility||'').trim()==='verified_anonymous';}),merged=[],ids={},urls={},removedIds={},removedUrls={},sources=verifiedCatalog.concat(apiFiles||[]);sources.forEach(function(raw){if(activeFile(raw))return;var id=String(raw&&raw.id||'').trim(),url=canonicalFileUrl(raw&&raw.url);if(id)removedIds[id]=true;if(url)removedUrls[url]=true;});function add(raw){var incoming=normalizedManagedFile(raw),urlKey=canonicalFileUrl(incoming.url),index=incoming.id&&ids[incoming.id]!==undefined?ids[incoming.id]:urlKey&&urls[urlKey]!==undefined?urls[urlKey]:-1;if(!incoming.url||removedIds[incoming.id]||removedUrls[urlKey])return;if(index>=0){var current=merged[index];Object.keys(incoming).forEach(function(key){if(incoming[key]!==''&&incoming[key]!==null&&incoming[key]!==undefined)current[key]=incoming[key];});incoming=normalizedManagedFile(current);}else{index=merged.length;merged.push(incoming);}if(incoming.id)ids[incoming.id]=index;if(urlKey)urls[urlKey]=index;var mergedUrl=canonicalFileUrl(incoming.url);if(mergedUrl)urls[mergedUrl]=index;}verifiedCatalog.forEach(add);(apiFiles||[]).forEach(add);return merged.sort(function(left,right){return(Date.parse(right.firstSeenAt||right.modifiedAt||right.createdAt||right.lessonDate||'')||0)-(Date.parse(left.firstSeenAt||left.modifiedAt||left.createdAt||left.lessonDate||'')||0);});}
  function isDriveFile(file){try{var host=new URL(file.url,window.location.href).hostname.toLowerCase();return host==='drive.google.com'||host==='docs.google.com';}catch(error){return false;}}
  function isRecentFile(file){var timestamp=Date.parse(file.firstSeenAt||'');if(!Number.isFinite(timestamp))return false;var age=Date.now()-timestamp;return age>=0&&age<=7*24*60*60*1000;}
  var localFiles=files.map(function(file,index){return{id:'local-'+index,course:file[0],lessonDate:file[1],title:file[2],url:file[3],fileType:fileTypeFrom(file[3],file[2]),createdAt:'',modifiedAt:'',firstSeenAt:'',visibility:'bundled',managed:false};});
  var managedFiles=[];
  function combinedFiles(){var combined=[],ids={},urls={};managedFiles.concat(localFiles).forEach(function(file){if(!activeFile(file))return;var id=String(file.id||'').trim(),url=canonicalFileUrl(file.url);if((id&&ids[id])||(url&&urls[url]))return;if(id)ids[id]=true;if(url)urls[url]=true;combined.push(file);});return combined;}
  function render(){var host=document.getElementById('fileGroups'),groups={},filter=requestedCourse(),all=combinedFiles(),visible=filter?all.filter(function(file){return courseKey(file.course)===filter;}):all;visible.forEach(function(file){(groups[file.course]||(groups[file.course]=[])).push(file);});host.replaceChildren();Object.keys(groups).forEach(function(subject){var section=el('section','file-group'),head=el('header');section.dataset.course=courseKey(subject);head.appendChild(el('span','',String(groups[subject].length)+' ARCHIVOS'));head.appendChild(el('h2','',subject));section.appendChild(head);var list=el('div','file-list');groups[subject].forEach(function(file){var row=el('label','file-row'),check=el('input'),recent=isRecentFile(file);row.dataset.fileId=file.id||'';row.dataset.fileSource=file.managed?'hub':'local';row.dataset.fileRecent=recent?'true':'false';if(file.visibility)row.dataset.fileVisibility=file.visibility;check.type='checkbox';check.value=file.url;check.setAttribute('aria-label','Seleccionar '+file.title);var copy=el('span','file-row-copy');copy.appendChild(el('strong','',file.title));var meta=el('small','file-row-meta');meta.appendChild(el('span','file-row-date',file.lessonDate||String(file.firstSeenAt||'').slice(0,10)||'Publicado'));meta.appendChild(el('span','file-badge file-badge-type',file.fileType||'ARCHIVO'));if(isDriveFile(file)){var drive=el('span','file-badge file-badge-drive','DRIVE');drive.dataset.fileBadge='drive';meta.appendChild(drive);}if(recent){var recentBadge=el('span','file-badge file-badge-recent','RECIENTE');recentBadge.dataset.fileBadge='recent';meta.appendChild(recentBadge);}copy.appendChild(meta);var open=el('a','','Abrir');open.href=file.url;open.target='_blank';open.rel='noopener noreferrer';row.appendChild(check);row.appendChild(copy);row.appendChild(open);list.appendChild(row);});section.appendChild(list);host.appendChild(section);});if(!Object.keys(groups).length)host.appendChild(el('p','file-empty','No hay archivos publicados para esta materia.'));var status=document.getElementById('fileStatus');if(status&&filter)status.textContent=visible.length+(visible.length===1?' archivo en la materia seleccionada.':' archivos en la materia seleccionada.');}
  function fetchJson(url){return fetch(url,{headers:{accept:'application/json'}}).then(function(response){if(!response.ok)throw new Error();return response.json();}).catch(function(){return{};});}
  function addDynamic(){Promise.all([fetchJson('/api/class-hub?class=s4-e&resource=public'),fetchJson('/data/drive-files.json')]).then(function(results){managedFiles=mergeManagedFiles(Array.isArray(results[1].files)?results[1].files:[],Array.isArray(results[0].files)?results[0].files:[]);render();});}
  function init(){render();addDynamic();var select=document.getElementById('selectAllFiles'),download=document.getElementById('downloadFiles'),status=document.getElementById('fileStatus');select.addEventListener('click',function(){var checks=document.querySelectorAll('.file-row input'),all=Array.prototype.every.call(checks,function(check){return check.checked;});checks.forEach(function(check){check.checked=!all;});select.textContent=all?'Seleccionar todo':'Quitar selección';});download.addEventListener('click',function(){var chosen=Array.prototype.slice.call(document.querySelectorAll('.file-row input:checked'));if(!chosen.length){status.textContent='Selecciona al menos un archivo.';return;}status.textContent='Iniciando '+chosen.length+' descargas…';chosen.forEach(function(check,index){setTimeout(function(){var link=el('a');link.href=check.value;link.download='';document.body.appendChild(link);link.click();link.remove();},index*250);});});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
