(function(){
  'use strict';
  function currentClass(){var path=location.pathname.match(/^\/gestion\/([a-z0-9-]+)\/?$/i),query=new URLSearchParams(location.search).get('class'),raw=String((path&&path[1])||query||'').trim().toLowerCase();if(!raw)return's4-e';return/^[a-z0-9][a-z0-9-]{0,30}$/.test(raw)?raw:'invalid-class';}
  var classSlug=currentClass(),API='/api/class-hub?class='+encodeURIComponent(classSlug),tokenKey='med-nykuto-management-token-v471:'+classSlug,csrfCookieName='__Host-med-nykuto-management-csrf',accessToken='',authMode='',state=null,resetEditorId='';
  function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function status(message,error){var target=document.getElementById('manageStatus');target.textContent=message||'';target.style.color=error?'#fca5a5':'#86efac';}
  function authStatus(message,error){var target=document.getElementById('authStatus');target.textContent=message||'';target.dataset.error=error?'true':'false';target.style.color=error?'#fca5a5':'#86efac';}
  function browserCookie(name){var prefix=name+'=',parts=document.cookie?document.cookie.split(';'):[];for(var index=0;index<parts.length;index+=1){var part=parts[index].trim();if(part.indexOf(prefix)!==0)continue;try{return decodeURIComponent(part.slice(prefix.length));}catch(error){return'';}}return'';}
  function request(resource,options){options=options||{};var useBearer=options.bearer!==false&&Boolean(accessToken),headers=Object.assign({'accept':'application/json'},options.headers||{}),fetchOptions={};if(useBearer)headers.authorization='Bearer '+accessToken;if(options.csrf&&!useBearer){var csrf=browserCookie(csrfCookieName);if(csrf)headers['x-csrf-token']=csrf;}Object.keys(options).forEach(function(key){if(key!=='bearer'&&key!=='csrf')fetchOptions[key]=options[key];});fetchOptions.headers=headers;fetchOptions.credentials='same-origin';return fetch(API+(resource?'&resource='+encodeURIComponent(resource):''),fetchOptions).then(function(response){return response.json().catch(function(){return{};}).then(function(body){if(!response.ok){var failure=new Error(body.error||body.message||'No se pudo completar la operación.');failure.httpStatus=response.status;failure.code=body.code||'';failure.retryAfter=response.headers.get('retry-after')||'';throw failure;}return body;});});}
  function formData(form){var data={};new FormData(form).forEach(function(value,key){data[key]=value;});form.querySelectorAll('input[type=checkbox]').forEach(function(input){data[input.name]=input.checked;});return data;}
  function post(data,authOptions){var options=authOptions&&typeof authOptions==='object'?authOptions:{bearer:authOptions!==false,csrf:authOptions!==false};return request('',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data),bearer:options.bearer!==false,csrf:Boolean(options.csrf)});}
  function setBusy(form,busy,message){var submit=form&&form.querySelector('button[type=submit]');if(!form||!submit)return;if(!submit.dataset.defaultLabel)submit.dataset.defaultLabel=submit.textContent;form.setAttribute('aria-busy',busy?'true':'false');submit.disabled=Boolean(busy);submit.textContent=busy?(message||'Procesando…'):submit.dataset.defaultLabel;}
  function clearBearer(){sessionStorage.removeItem(tokenKey);accessToken='';if(authMode==='bearer')authMode='';}
  function showLogin(message,error){document.getElementById('authCard').hidden=false;document.getElementById('authMethods').hidden=false;document.getElementById('passwordChangeCard').hidden=true;document.getElementById('manageApp').hidden=true;if(message!==undefined)authStatus(message,error);}
  function showPasswordChange(message){document.getElementById('authCard').hidden=false;document.getElementById('authMethods').hidden=true;document.getElementById('passwordChangeCard').hidden=false;document.getElementById('manageApp').hidden=true;authStatus(message||'Crea una contraseña personal para continuar.');var input=document.getElementById('newPassword');input.value='';document.getElementById('confirmPassword').value='';setTimeout(function(){input.focus();},0);}
  function card(eyebrow,title,detail){var item=el('article','manage-item'),copy=el('div');copy.appendChild(el('span','',eyebrow));copy.appendChild(el('strong','',title));if(detail)copy.appendChild(el('small','',detail));item.appendChild(copy);return item;}
  function empty(target,text){target.replaceChildren(el('p','empty',text));}
  function field(form,name){return form.elements.namedItem(name);}
  function setField(form,name,value){var input=field(form,name);if(!input)return;if(input.type==='checkbox')input.checked=Boolean(value);else input.value=value==null?'':String(value);}
  function localDateTime(value){var text=String(value||'');if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(text))return text.slice(0,16);return text;}
  function normalizedSubject(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
  function simpleStatus(value){return value==='published'?'Publicado':value==='archived'?'Archivado':value==='active'?'Activo':'Borrador';}
  function simplePriority(value){return value==='urgent'?'Urgente':value==='important'?'Importante':'Normal';}
  function taskValue(task,camel,snake){return task[camel]!==undefined?task[camel]:task[snake];}
  function subjectIdForCourse(course){var key=normalizedSubject(course),exact=(state.subjects||[]).find(function(subject){return normalizedSubject(subject.name)===key;});if(exact)return exact.id;var candidates=(state.subjects||[]).filter(function(subject){var subjectKey=normalizedSubject(subject.name);return key&&subjectKey&&(subjectKey.indexOf(key)===0||key.indexOf(subjectKey)===0);});return candidates.length===1?candidates[0].id:'';}
  function refreshTaskDateOptions(selectedValue){var select=document.getElementById('taskSuggestedDate'),course=document.getElementById('taskCourseInput').value.trim(),subjectId=subjectIdForCourse(course),courseKey=normalizedSubject(course),dates=(state&&state.upcomingDates||[]).filter(function(item){if(subjectId&&item.subjectId)return item.subjectId===subjectId;return courseKey&&normalizedSubject(item.subject)===courseKey;}).sort(function(left,right){return String(left.startsAt||'').localeCompare(String(right.startsAt||''));});select.replaceChildren();var placeholder=el('option','',course?(dates.length?'Selecciona una de las próximas clases':'No hay próximas clases configuradas'):'Selecciona primero una materia');placeholder.value='';select.appendChild(placeholder);dates.forEach(function(item){var slot=(state.scheduleSlots||[]).find(function(candidate){return candidate.id===item.slotId;}),option=el('option','',item.label+(slot&&slot.label?' · '+slot.label:''));option.value=localDateTime(item.startsAt);option.dataset.dueLabel=item.label||'';select.appendChild(option);});var match=localDateTime(selectedValue||document.getElementById('taskDueAtInput').value);if(match&&Array.prototype.some.call(select.options,function(option){return option.value===match;}))select.value=match;select.disabled=!course||!dates.length;}
  function bindTaskDateSuggestions(){var course=document.getElementById('taskCourseInput'),suggested=document.getElementById('taskSuggestedDate'),dueAt=document.getElementById('taskDueAtInput'),dueLabel=field(document.getElementById('taskForm'),'dueLabel');function update(){refreshTaskDateOptions(dueAt.value);}course.addEventListener('input',update);course.addEventListener('change',update);dueAt.addEventListener('change',function(){refreshTaskDateOptions(dueAt.value);});suggested.addEventListener('change',function(){if(!suggested.value)return;dueAt.value=localDateTime(suggested.value);var option=suggested.options[suggested.selectedIndex];if(option&&option.dataset.dueLabel)dueLabel.value=option.dataset.dueLabel;dueAt.dispatchEvent(new Event('change',{bubbles:true}));});document.getElementById('taskForm').addEventListener('reset',function(){setTimeout(function(){refreshTaskDateOptions('');},0);});}
  function bindPasswordToggles(root){(root||document).querySelectorAll('[data-password-toggle]').forEach(function(button){if(button.dataset.bound==='true')return;var input=document.getElementById(button.getAttribute('aria-controls'));if(!input)return;button.dataset.bound='true';button.addEventListener('click',function(){var reveal=input.type==='password';input.type=reveal?'text':'password';button.setAttribute('aria-pressed',reveal?'true':'false');var action=reveal?'Ocultar':'Mostrar',label=(input.id==='accessToken'?' token':input.id==='inviteToken'?' código de invitación':' contraseña');button.setAttribute('aria-label',action+label);button.title=action+label;var hidden=button.querySelector('.sr-only');if(hidden)hidden.textContent=action+label;input.focus({preventScroll:true});});});}
  function showForm(tab,formId,values,label){var tabButton=document.querySelector('[data-manage-tab="'+tab+'"]'),form=document.getElementById(formId);if(tabButton)tabButton.click();Object.keys(values).forEach(function(name){setField(form,name,values[name]);});if(formId==='taskForm')refreshTaskDateOptions(values.dueAt);var advanced=field(form,'id');if(advanced&&advanced.value){var details=advanced.closest('details');if(details)details.open=true;}if(formId==='classForm'){field(form,'slug').readOnly=true;form.dataset.originalStatus=values.status||'active';var archiveOption=field(form,'status').querySelector('option[value="archived"]');if(archiveOption)archiveOption.disabled=values.slug==='s4-e';document.getElementById('classFormTitle').textContent='Modificar clase';}var submit=form.querySelector('button[type=submit]');if(submit){if(!submit.dataset.defaultLabel)submit.dataset.defaultLabel=submit.textContent;submit.textContent=label;}form.dataset.editing='true';form.scrollIntoView({behavior:'smooth',block:'start'});var first=form.querySelector('input:not([type=hidden]),select,textarea');if(first)first.focus({preventScroll:true});}
  function clearEditMode(form){delete form.dataset.editing;var submit=form.querySelector('button[type=submit]');if(submit&&submit.dataset.defaultLabel)submit.textContent=submit.dataset.defaultLabel;if(form.getAttribute('id')==='classForm'){delete form.dataset.originalStatus;field(form,'slug').readOnly=false;field(form,'slug').removeAttribute('readonly');var archiveOption=field(form,'status').querySelector('option[value="archived"]');if(archiveOption)archiveOption.disabled=false;document.getElementById('classFormTitle').textContent='Nueva clase';}form.querySelectorAll('details.advanced-fields').forEach(function(details){details.open=false;});}
  function actionButtons(edit,archive,isArchived){var actions=el('div','manage-item-actions'),editButton=el('button','','Modificar');editButton.type='button';editButton.addEventListener('click',edit);actions.appendChild(editButton);if(!isArchived){var archiveButton=el('button','archive-action','Archivar');archiveButton.type='button';archiveButton.addEventListener('click',archive);actions.appendChild(archiveButton);}return actions;}
  function copyText(value){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(value);return new Promise(function(resolve,reject){var input=document.createElement('textarea');input.value=value;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();try{if(!document.execCommand('copy'))throw new Error('copy_failed');resolve();}catch(error){reject(error);}finally{input.remove();}});}
  function populateLookups(){var subjects=[],seen={};(state.subjects||[]).concat((state.tasks||[]).map(function(item){return {name:item.course};}),(state.files||[]).map(function(item){return {name:item.course};})).forEach(function(subject){var name=String(subject.name||'').trim(),key=name.toLowerCase();if(!name||seen[key])return;seen[key]=true;subjects.push(name);});subjects.sort(function(left,right){return left.localeCompare(right,'es');});var subjectOptions=document.getElementById('subjectOptions');subjectOptions.replaceChildren();subjects.forEach(function(name){var option=el('option');option.value=name;subjectOptions.appendChild(option);});refreshTaskDateOptions(document.getElementById('taskDueAtInput').value);var activitySelect=document.getElementById('groupActivitySelect'),selected=activitySelect.value;activitySelect.replaceChildren();var placeholder=el('option','','Selecciona una actividad');placeholder.value='';activitySelect.appendChild(placeholder);(state.activities||[]).forEach(function(activity){var option=el('option','',activity.title+(activityLocked(activity)?' · cerrada':activity.status==='archived'?' · archivada':''));option.value=activity.id;option.disabled=activityLocked(activity)||activity.status==='archived';activitySelect.appendChild(option);});if(Array.prototype.some.call(activitySelect.options,function(option){return option.value===selected&&!option.disabled;}))activitySelect.value=selected;}
  function renderTasks(){var target=document.getElementById('taskList');target.replaceChildren();(state.tasks||[]).forEach(function(task){var dueLabel=taskValue(task,'dueLabel','due_label')||'Sin fecha',dueAt=taskValue(task,'dueAt','due_at')||'',attachmentUrl=taskValue(task,'attachmentUrl','attachment_url')||'',attachmentTitle=taskValue(task,'attachmentTitle','attachment_title')||'',details=[dueLabel];if(task.description)details.push(task.description);if(attachmentUrl)details.push('Archivo: '+(attachmentTitle||'Documento adjunto'));var item=card(simpleStatus(task.status)+' · '+task.course,task.title,details.join(' · '));item.querySelector('span').classList.add('status-'+task.status);item.appendChild(actionButtons(function(){showForm('tasks','taskForm',{id:task.id,course:task.course,title:task.title,description:task.description,dueLabel:dueLabel==='Sin fecha'?'':dueLabel,dueAt:localDateTime(dueAt),attachmentUrl:attachmentUrl,attachmentTitle:attachmentTitle,status:task.status},'Actualizar tarea');},function(){if(confirm('¿Archivar la tarea «'+task.title+'»?'))mutate({action:'task.upsert',id:task.id,course:task.course,title:task.title,description:task.description||'',dueLabel:dueLabel==='Sin fecha'?'':dueLabel,dueAt:dueAt,attachmentUrl:attachmentUrl,attachmentTitle:attachmentTitle,status:'archived'});},task.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay tareas guardadas.');}
  function renderNotices(){var target=document.getElementById('noticeList');target.replaceChildren();(state.notices||[]).forEach(function(notice){var item=card(simplePriority(notice.priority)+' · '+simpleStatus(notice.status),notice.title,notice.body);item.querySelector('span').classList.add('status-'+notice.status);item.appendChild(actionButtons(function(){showForm('notices','noticeForm',{id:notice.id,priority:notice.priority,title:notice.title,body:notice.body,status:notice.status,pushMode:Boolean(notice.push_mode)},'Actualizar aviso');},function(){if(confirm('¿Archivar el aviso «'+notice.title+'»?'))mutate({action:'notice.upsert',id:notice.id,priority:notice.priority,title:notice.title,body:notice.body||'',status:'archived',pushMode:Boolean(notice.push_mode)});},notice.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay avisos guardados.');}
  function groupMembers(groupId){return (state.memberships||[]).filter(function(member){return member.group_id===groupId;});}
  function activityLocked(activity){return Boolean(activity.frozen||(activity.closes_at&&new Date(activity.closes_at).getTime()<=Date.now()));}
  function renderGroups(){var target=document.getElementById('groupList');target.replaceChildren();(state.activities||[]).forEach(function(activity){var locked=activityLocked(activity),activityGroups=(state.groups||[]).filter(function(group){return group.activity_id===activity.id;}),activityItem=card(simpleStatus(activity.status)+(locked?' · Cambios cerrados':''),activity.title,'Máximo '+activity.capacity+' estudiantes por grupo'+(activity.closes_at?' · cierre '+activity.closes_at:''));var wrap=el('div');activityGroups.forEach(function(group){var members=groupMembers(group.id),groupDetail=members.length+'/'+group.capacity+' integrantes'+(group.topic?' · Tema: '+group.topic:''),groupItem=card(group.frozen||locked?'Cambios cerrados':'Cambios abiertos',group.name,groupDetail),memberList=el('div','member-list');members.slice().sort(function(left,right){return Number(Boolean(right.isLeader||right.is_leader))-Number(Boolean(left.isLeader||left.is_leader));}).forEach(function(member){var leader=Boolean(member.isLeader||member.is_leader),chip=el('span','member-chip'+(leader?' member-leader':''),member.display_name+(leader?' · Responsable':'')),controls=el('span','member-controls'),move=el('select','member-move'),moveButton=el('button','','Mover'),remove=el('button','','Quitar');activityGroups.forEach(function(candidate){if(candidate.id===group.id)return;var option=el('option','',candidate.name);option.value=candidate.id;option.disabled=Boolean(candidate.frozen||groupMembers(candidate.id).length>=Math.min(candidate.capacity,activity.capacity));move.appendChild(option);});moveButton.type='button';moveButton.disabled=locked||!move.options.length;move.disabled=moveButton.disabled;moveButton.addEventListener('click',function(){if(move.value)mutate({action:'member.move',id:member.id,groupId:move.value});});remove.type='button';remove.disabled=locked;remove.addEventListener('click',function(){if(!confirm('¿Quitar a '+member.display_name+' del grupo?'))return;mutate({action:'member.remove',id:member.id});});controls.appendChild(move);controls.appendChild(moveButton);controls.appendChild(remove);chip.appendChild(controls);memberList.appendChild(chip);});groupItem.firstChild.appendChild(memberList);wrap.appendChild(groupItem);});activityItem.firstChild.appendChild(wrap);target.appendChild(activityItem);});if(!target.children.length)empty(target,'No hay actividades de grupo.');}
  function renderFiles(){var target=document.getElementById('fileList');target.replaceChildren();(state.files||[]).forEach(function(file){var item=card(file.status.toUpperCase()+' · '+file.course,file.title,file.url);item.querySelector('span').classList.add('status-'+file.status);item.appendChild(actionButtons(function(){showForm('files','fileForm',{id:file.id,course:file.course,lessonDate:file.lesson_date,title:file.title,url:file.url,fileType:file.file_type,status:file.status},'Actualizar archivo');},function(){if(confirm('¿Archivar el archivo «'+file.title+'»?'))mutate({action:'file.upsert',id:file.id,course:file.course,lessonDate:file.lesson_date||'',title:file.title,url:file.url,fileType:file.file_type||'',status:'archived'});},file.status==='archived'));target.appendChild(item);});(state.dates||[]).forEach(function(date){var item=card(date.status.toUpperCase()+' · FECHA',date.label,date.starts_at);item.querySelector('span').classList.add('status-'+date.status);item.appendChild(actionButtons(function(){showForm('files','dateForm',{id:date.id,label:date.label,startsAt:localDateTime(date.starts_at),status:date.status},'Actualizar fecha');},function(){if(confirm('¿Archivar la fecha «'+date.label+'»?'))mutate({action:'date.upsert',id:date.id,label:date.label,startsAt:date.starts_at,status:'archived'});},date.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay archivos ni fechas dinámicas.');}
  function renderInvites(){var target=document.getElementById('inviteList');if(!target)return;target.replaceChildren();(state.invites||[]).forEach(function(invite){var active=!invite.revoked_at&&!invite.claimed_at&&new Date(invite.expires_at).getTime()>Date.now(),label=invite.claimed_at?'UTILIZADA':invite.revoked_at?'REVOCADA':active?'ACTIVA':'CADUCADA',item=card(label,invite.label,'Vence: '+invite.expires_at),actions=el('div','manage-item-actions');if(active){var revoke=el('button','','Revocar invitación');revoke.type='button';revoke.addEventListener('click',function(){if(confirm('¿Revocar esta invitación?'))mutate({action:'invite.revoke',id:invite.id});});actions.appendChild(revoke);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay invitaciones recientes.');}
  function openPasswordReset(editor){var dialog=document.getElementById('resetPasswordDialog'),form=document.getElementById('resetPasswordForm');resetEditorId=editor.id;setField(form,'id',editor.id);setField(form,'temporaryPassword','');setField(form,'hours','24');document.getElementById('resetPasswordEditor').textContent='La nueva contraseña temporal de '+editor.name+' caducará y deberá cambiarse al entrar.';if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');setTimeout(function(){field(form,'temporaryPassword').focus();},0);}
  function renderEditors(){var target=document.getElementById('editorList');target.replaceChildren();(state.editors||[]).forEach(function(editor){var details=[];if(editor.email)details.push(editor.email);details.push(editor.last_used_at?'Último uso: '+editor.last_used_at:'Todavía sin uso');if(editor.password_change_required)details.push('Cambio de contraseña pendiente');var item=card(editor.status.toUpperCase(),editor.name,details.join(' · ')),actions=el('div','manage-item-actions');if(editor.status==='active'){if(editor.email){var reset=el('button','','Restablecer contraseña');reset.type='button';reset.addEventListener('click',function(){openPasswordReset(editor);});actions.appendChild(reset);}var revoke=el('button','','Revocar');revoke.type='button';revoke.addEventListener('click',function(){if(confirm('¿Revocar el acceso de '+editor.name+'?'))mutate({action:'editor.revoke',id:editor.id});});actions.appendChild(revoke);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay editores activos.');}
  function renderSubjectsAdmin(){var target=document.getElementById('subjectListAdmin');if(!target)return;target.replaceChildren();(state.subjects||[]).forEach(function(subject){target.appendChild(card('ORDEN '+String(subject.order||0),subject.name,subject.id));});if(!target.children.length)empty(target,'No hay materias configuradas en esta clase.');}
  function classMutation(info,nextStatus){return {action:'class.upsert',id:info.id,slug:info.slug,name:info.name,semester:info.semester,group:info.group||'',theme:info.theme||'midnight-gold',driveUrl:info.driveUrl||'',status:nextStatus};}
  function renderClasses(){if(state.actor.role!=='owner')return;request('classes').then(function(data){var target=document.getElementById('classList');target.replaceChildren();(data.classes||[]).forEach(function(info){var archived=info.status==='archived',item=card((archived?'ARCHIVADA':'ACTIVA')+' · SEMESTRE '+info.semester+(info.group?' · GRUPO '+info.group:''),info.name,info.slug),actions=el('div','manage-item-actions'),edit=el('button','','Modificar');item.querySelector('span').classList.add('status-'+info.status);edit.type='button';edit.addEventListener('click',function(){showForm('classes','classForm',{id:info.id,slug:info.slug,name:info.name,semester:info.semester,group:info.group||'',theme:info.theme||'midnight-gold',driveUrl:info.driveUrl||'',status:info.status},'Actualizar clase');});actions.appendChild(edit);if(archived){var reactivate=el('button','','Reactivar');reactivate.type='button';reactivate.addEventListener('click',function(){mutate(classMutation(info,'active'));});actions.appendChild(reactivate);}else{var open=el('a','','Abrir gestión'),space=el('a','','Ver clase');open.href='/gestion/'+encodeURIComponent(info.slug);space.href='/turma/'+encodeURIComponent(info.slug);actions.appendChild(open);actions.appendChild(space);if(info.slug!=='s4-e'){var archive=el('button','archive-action','Archivar');archive.type='button';archive.addEventListener('click',function(){if(confirm('¿Archivar la clase «'+info.name+'»? Su espacio dejará de estar disponible, pero sus datos se conservarán.'))mutate(classMutation(info,'archived'));});actions.appendChild(archive);}}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay clases registradas.');}).catch(function(error){status(error.message,true);});}
  function renderAudit(){if(state.actor.role!=='owner')return;request('audit').then(function(data){var target=document.getElementById('auditList');target.replaceChildren();(data.audit||[]).forEach(function(entry){target.appendChild(card(entry.actor_role.toUpperCase()+' · '+entry.action,entry.entity_type+' · '+entry.entity_id,entry.created_at));});if(!target.children.length)empty(target,'El registro está vacío.');}).catch(function(error){status(error.message,true);});}
  function render(){var info=state.class||{slug:classSlug,name:classSlug.toUpperCase()};document.getElementById('actorRole').textContent=state.actor.role==='owner'?'PROPIETARIO':'DELEGADO';document.getElementById('actorName').textContent=state.actor.name+' · '+(info.name||classSlug.toUpperCase());document.getElementById('manageClassLabel').textContent='Gestión · '+(info.name||classSlug.toUpperCase());document.getElementById('manageClassTitle').textContent='Panel de la clase · '+(info.name||classSlug.toUpperCase());document.getElementById('subjectClassLabel').textContent=(info.slug||classSlug).toUpperCase();document.querySelectorAll('[data-owner-only]').forEach(function(node){node.hidden=state.actor.role!=='owner';});populateLookups();renderTasks();renderNotices();renderGroups();renderFiles();renderInvites();renderEditors();renderSubjectsAdmin();renderClasses();renderAudit();}
  function load(){status('Cargando…');return request('admin').then(function(data){state=data;document.getElementById('authCard').hidden=true;document.getElementById('manageApp').hidden=false;status('Datos sincronizados.');authStatus('');render();var title=document.getElementById('manageClassTitle');setTimeout(function(){title.focus({preventScroll:true});},0);return data;}).catch(function(error){var terminal=error.httpStatus===400||error.httpStatus===401||error.httpStatus===403||error.httpStatus===404||error.httpStatus===410;if(error.code==='password_change_required'&&!accessToken){authMode='session';showPasswordChange(error.message);throw error;}if(state&&!terminal){status('Sincronización pendiente: los datos cargados y el formulario se mantienen.',true);return state;}if(terminal)clearBearer();showLogin(error.message,true);throw error;});}
  function mutate(data){status('Guardando…');return post(data,true).then(function(result){status('Cambio guardado y auditado.');if(data.action==='class.upsert'&&result.class&&result.class.slug===classSlug&&result.class.status==='archived'){sessionStorage.removeItem(tokenKey);location.href='/gestion/s4-e';return result;}return load().then(function(){return result;});}).catch(function(error){status(error.message,true);return null;});}
  function bindForm(id,reset){var form=document.getElementById(id);form.addEventListener('submit',function(event){event.preventDefault();var data=formData(form);mutate(data).then(function(result){if(result&&reset){form.reset();clearEditMode(form);}});});}
  function bindTabs(){document.querySelectorAll('[data-manage-tab]').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('[data-manage-tab]').forEach(function(item){item.setAttribute('aria-selected',item===button?'true':'false');});document.querySelectorAll('[data-manage-panel]').forEach(function(panel){panel.hidden=panel.dataset.managePanel!==button.dataset.manageTab;});});});}
  function exportText(){var lines=['*Grupos Med Nykuto*'];(state.activities||[]).forEach(function(activity){lines.push('', '*'+activity.title+'*');(state.groups||[]).filter(function(group){return group.activity_id===activity.id;}).forEach(function(group){var names=groupMembers(group.id).map(function(member){return member.display_name;});lines.push(group.name+' ('+names.length+'/'+group.capacity+'): '+(names.join(', ')||'sin integrantes'));});});return lines.join('\n');}
  function resetAuth(message){state=null;clearBearer();authMode='';document.getElementById('loginPassword').value='';document.getElementById('accessToken').value='';showLogin(message||'Sesión cerrada correctamente.',false);setTimeout(function(){document.getElementById('loginEmail').focus();},0);}
  function logout(){var buttons=document.querySelectorAll('#logoutButton,#passwordChangeLogout'),inManagement=!document.getElementById('manageApp').hidden;buttons.forEach(function(button){button.disabled=true;});if(inManagement)status('Cerrando sesión…');else authStatus('Cerrando sesión…');return post({action:'auth.logout'},{bearer:false,csrf:true}).then(function(){resetAuth('Sesión cerrada correctamente.');}).catch(function(error){if(inManagement)status(error.message,true);else authStatus(error.message,true);}).finally(function(){buttons.forEach(function(button){button.disabled=false;});});}
  function restoreSession(){authStatus('Comprobando sesión segura…');return request('session',{bearer:false}).then(function(data){authMode='session';if(data.passwordChangeRequired){showPasswordChange();return data;}return load();}).catch(function(error){if(error.code==='password_change_required'){authMode='session';showPasswordChange(error.message);return null;}if(error.httpStatus===401||error.httpStatus===403){showLogin('',false);return null;}showLogin(error.message,true);return null;});}
  function bindCredentialAuth(){
    var credentialForm=document.getElementById('credentialForm'),email=document.getElementById('loginEmail'),password=document.getElementById('loginPassword'),passwordForm=document.getElementById('passwordChangeForm'),newPassword=document.getElementById('newPassword'),confirmation=document.getElementById('confirmPassword');
    [email,password].forEach(function(input){input.setAttribute('aria-describedby','authStatus');input.addEventListener('input',function(){input.removeAttribute('aria-invalid');});});
    [newPassword,confirmation].forEach(function(input){input.setAttribute('aria-describedby','authStatus');input.addEventListener('input',function(){input.setCustomValidity('');input.removeAttribute('aria-invalid');});});
    credentialForm.addEventListener('submit',function(event){event.preventDefault();email.removeAttribute('aria-invalid');password.removeAttribute('aria-invalid');clearBearer();setBusy(credentialForm,true,'Verificando…');authStatus('Verificando la cuenta…');post({action:'auth.login',email:email.value.trim(),password:password.value},false).then(function(data){password.value='';authMode='session';if(data.passwordChangeRequired){showPasswordChange();return data;}return load();}).catch(function(error){password.value='';email.setAttribute('aria-invalid','true');password.setAttribute('aria-invalid','true');authStatus(error.message,true);password.focus();}).finally(function(){setBusy(credentialForm,false);});});
    passwordForm.addEventListener('submit',function(event){event.preventDefault();newPassword.setCustomValidity('');confirmation.setCustomValidity('');if(newPassword.value!==confirmation.value){confirmation.setCustomValidity('Las contraseñas no coinciden.');confirmation.setAttribute('aria-invalid','true');authStatus('Las contraseñas no coinciden.',true);confirmation.reportValidity();confirmation.focus();return;}setBusy(passwordForm,true,'Guardando…');authStatus('Protegiendo la nueva contraseña…');post({action:'auth.password.change',password:newPassword.value},true).then(function(){newPassword.value='';confirmation.value='';authMode='session';document.getElementById('passwordChangeCard').hidden=true;return load();}).catch(function(error){newPassword.value='';confirmation.value='';newPassword.setAttribute('aria-invalid','true');confirmation.setAttribute('aria-invalid','true');authStatus(error.message,true);newPassword.focus();}).finally(function(){setBusy(passwordForm,false);});});
    var passwordLogout=el('button','password-change-logout','Cerrar sesión');passwordLogout.id='passwordChangeLogout';passwordLogout.type='button';passwordLogout.addEventListener('click',logout);document.getElementById('passwordChangeCard').appendChild(passwordLogout);
  }
  function bindPasswordReset(){
    var dialog=el('dialog','credential-dialog'),form=el('form'),heading=el('h2','','Restablecer contraseña temporal'),description=el('p','','Med Nykuto no vuelve a mostrar ni registrar la contraseña después de guardarla.'),editor=el('p',''),id=el('input'),passwordLabel=el('label','', 'Nueva contraseña temporal'),password=el('input'),hoursLabel=el('label','', 'Validez en horas'),hours=el('input'),actions=el('div','credential-dialog-actions'),cancel=el('button','','Cancelar'),submit=el('button','','Guardar contraseña temporal');
    dialog.id='resetPasswordDialog';dialog.setAttribute('aria-labelledby','resetPasswordTitle');heading.id='resetPasswordTitle';editor.id='resetPasswordEditor';form.id='resetPasswordForm';id.type='hidden';id.name='id';password.type='password';password.name='temporaryPassword';password.autocomplete='new-password';password.minLength=6;password.maxLength=128;password.required=true;hours.type='number';hours.name='hours';hours.min='1';hours.max='24';hours.value='24';cancel.type='button';submit.type='submit';passwordLabel.appendChild(password);hoursLabel.appendChild(hours);actions.appendChild(cancel);actions.appendChild(submit);form.appendChild(heading);form.appendChild(description);form.appendChild(editor);form.appendChild(id);form.appendChild(passwordLabel);form.appendChild(hoursLabel);form.appendChild(actions);dialog.appendChild(form);document.body.appendChild(dialog);
    cancel.addEventListener('click',function(){if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');});dialog.addEventListener('close',function(){resetEditorId='';password.value='';form.reset();hours.value='24';});
    form.addEventListener('submit',function(event){event.preventDefault();if(!resetEditorId||field(form,'id').value!==resetEditorId){status('No se pudo identificar al delegado.',true);return;}var data=formData(form);data.action='editor.password.reset';setBusy(form,true,'Guardando…');mutate(data).then(function(result){password.value='';if(!result)return;if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');status('Contraseña temporal actualizada. Debe comunicarse por un canal privado.');}).finally(function(){password.value='';setBusy(form,false);});});
  }
  function bindActions(){
    document.getElementById('freezeGroups').addEventListener('click',function(){var select=document.getElementById('groupActivitySelect'),id=select.value;if(!id){status('Selecciona primero una actividad abierta.',true);select.focus();return;}if(confirm('¿Congelar la actividad seleccionada? Los integrantes ya no podrán cambiar de grupo.'))mutate({action:'group.freeze',activityId:id,frozen:true});});
    document.getElementById('exportWhatsapp').addEventListener('click',function(){copyText(exportText()).then(function(){status('Resumen copiado para WhatsApp.');}).catch(function(){status('No se pudo copiar automáticamente.',true);});});
    document.getElementById('exportPdf').addEventListener('click',function(){var popup=window.open('','_blank');if(!popup){status('Permite ventanas emergentes para exportar el PDF.',true);return;}popup.opener=null;var text=exportText().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/\n/g,'<br>');popup.document.write('<!doctype html><html><head><title>Grupos Med Nykuto</title><style>body{font:16px/1.6 system-ui;padding:36px;color:#111}h1{color:#075985}</style></head><body><h1>Grupos Med Nykuto</h1><p>'+text+'</p><script>print()<\/script></body></html>');popup.document.close();});
    document.getElementById('logoutButton').addEventListener('click',logout);
  }
  function init(){
    var classHome='/turma/'+encodeURIComponent(classSlug),manageTitle=document.getElementById('manageClassTitle'),passwordTitle=document.getElementById('passwordChangeTitle'),authStatusNode=document.getElementById('authStatus');document.getElementById('manageClassHome').href=classHome;document.getElementById('manageBackLink').href=classHome;document.getElementById('manageClassLabel').textContent='Gestión · '+classSlug.toUpperCase();document.getElementById('authClassSlug').textContent=classSlug.toUpperCase();document.getElementById('inviteLabel').value='Editor '+classSlug.toUpperCase();manageTitle.tabIndex=-1;passwordTitle.tabIndex=-1;authStatusNode.setAttribute('aria-atomic','true');
    bindTabs();bindPasswordToggles(document);bindTaskDateSuggestions();['taskForm','noticeForm','activityForm','groupForm','fileForm','dateForm','subjectForm'].forEach(function(id){bindForm(id,true);});
    document.getElementById('classForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget,data=formData(form),wasEditing=form.dataset.editing==='true';if(data.status==='archived'&&form.dataset.originalStatus!=='archived'&&!confirm('¿Archivar esta clase? Su espacio dejará de estar disponible, pero sus datos se conservarán.'))return;mutate(data).then(function(result){if(!result||!result.class)return;var info=result.class,output=document.getElementById('classOutput');output.hidden=false;output.replaceChildren(document.createTextNode((wasEditing?'Clase actualizada: ':'Clase creada: ')+info.name+'. '));if(info.status==='active'){var manage=el('a','','Configurar ahora');manage.href='/gestion/'+encodeURIComponent(info.slug);output.appendChild(manage);}else output.appendChild(document.createTextNode('Está archivada; reactívala desde la lista para configurarla.'));form.reset();clearEditMode(form);});});
    document.getElementById('inviteForm').addEventListener('submit',function(event){event.preventDefault();var data=formData(event.currentTarget);mutate(data).then(function(result){if(!result||!result.inviteToken)return;var output=document.getElementById('inviteOutput'),heading=el('strong','','Invitación creada · se muestra una sola vez'),token=el('code','invite-token',result.inviteToken),expiry=el('small','invite-expiry','Vence: '+result.expiresAt),copy=el('button','','Copiar invitación');copy.type='button';copy.addEventListener('click',function(){copyText(result.inviteToken).then(function(){copy.textContent='Invitación copiada';status('Token de invitación copiado.');}).catch(function(){status('No se pudo copiar automáticamente. Selecciona el token y cópialo manualmente.',true);});});output.hidden=false;output.replaceChildren(heading,token,expiry,copy);});});
    document.getElementById('delegateAccountForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget,data=formData(form),temporaryPassword=field(form,'temporaryPassword');setBusy(form,true,'Creando…');mutate(data).then(function(result){temporaryPassword.value='';if(!result||!result.editor)return;var output=document.getElementById('accountOutput'),heading=el('strong','','Cuenta de delegado creada'),details=el('small','',result.editor.name+' · '+result.editor.email),expiry=el('small','account-expiry','Contraseña temporal válida hasta: '+result.temporaryExpiresAt);output.hidden=false;output.replaceChildren(heading,details,expiry);form.reset();field(form,'hours').value='24';}).finally(function(){temporaryPassword.value='';setBusy(form,false);});});
    bindCredentialAuth();bindPasswordReset();
    bindActions();
    document.getElementById('tokenForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget;accessToken=document.getElementById('accessToken').value.trim();authMode='bearer';sessionStorage.setItem(tokenKey,accessToken);setBusy(form,true,'Verificando…');load().then(function(){document.getElementById('accessToken').value='';}).catch(function(){}).finally(function(){setBusy(form,false);});});
    document.getElementById('claimForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget;authStatus('Activando…');setBusy(form,true,'Activando…');post({action:'invite.claim',inviteToken:document.getElementById('inviteToken').value.trim(),name:document.getElementById('inviteName').value.trim()},false).then(function(data){accessToken=data.editorToken;authMode='bearer';sessionStorage.setItem(tokenKey,accessToken);return load();}).catch(function(error){authStatus(error.message,true);}).finally(function(){setBusy(form,false);});});
    accessToken=sessionStorage.getItem(tokenKey)||'';if(accessToken){authMode='bearer';load().catch(function(){return restoreSession();});}else restoreSession();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
