(function(){
  'use strict';
  function currentClass(){var path=location.pathname.match(/^\/gestion\/([a-z0-9-]+)\/?$/i),query=new URLSearchParams(location.search).get('class'),raw=String((path&&path[1])||query||'').trim().toLowerCase();if(!raw)return's4-e';return/^[a-z0-9][a-z0-9-]{0,30}$/.test(raw)?raw:'invalid-class';}
  var classSlug=currentClass(),API='/api/class-hub?class='+encodeURIComponent(classSlug),tokenKey='med-nykuto-management-token-v471:'+classSlug,csrfCookieName='__Host-med-nykuto-management-csrf',accessToken='',authMode='',state=null,resetEditorId='',noticeObjectUrl='',noticeAttachmentBaseline={};
  function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function status(message,error){var target=document.getElementById('manageStatus');target.textContent=message||'';target.style.color=error?'#fca5a5':'#86efac';}
  function authStatus(message,error){var target=document.getElementById('authStatus');target.textContent=message||'';target.dataset.error=error?'true':'false';target.style.color=error?'#fca5a5':'#86efac';}
  function browserCookie(name){var prefix=name+'=',parts=document.cookie?document.cookie.split(';'):[];for(var index=0;index<parts.length;index+=1){var part=parts[index].trim();if(part.indexOf(prefix)!==0)continue;try{return decodeURIComponent(part.slice(prefix.length));}catch(error){return'';}}return'';}
  function request(resource,options){options=options||{};var useBearer=options.bearer!==false&&Boolean(accessToken),headers=Object.assign({'accept':'application/json'},options.headers||{}),fetchOptions={};if(useBearer)headers.authorization='Bearer '+accessToken;if(options.csrf&&!useBearer){var csrf=browserCookie(csrfCookieName);if(csrf)headers['x-csrf-token']=csrf;}Object.keys(options).forEach(function(key){if(key!=='bearer'&&key!=='csrf')fetchOptions[key]=options[key];});fetchOptions.headers=headers;fetchOptions.credentials='same-origin';return fetch(API+(resource?'&resource='+encodeURIComponent(resource):''),fetchOptions).then(function(response){return response.json().catch(function(){return{};}).then(function(body){if(!response.ok){var failure=new Error(body.error||body.message||'No se pudo completar la operación.');failure.httpStatus=response.status;failure.code=body.code||'';failure.retryAfter=response.headers.get('retry-after')||'';throw failure;}return body;});});}
  function formData(form){var data={};new FormData(form).forEach(function(value,key){data[key]=value;});form.querySelectorAll('input[type=checkbox]').forEach(function(input){data[input.name]=input.checked;});return data;}
  function post(data,authOptions){var options=authOptions&&typeof authOptions==='object'?authOptions:{bearer:authOptions!==false,csrf:authOptions!==false};return request('',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data),bearer:options.bearer!==false,csrf:Boolean(options.csrf)});}
  function uploadNoticeFile(file){var useBearer=Boolean(accessToken),headers={accept:'application/json'},body=new FormData();body.append('file',file,file.name);if(useBearer)headers.authorization='Bearer '+accessToken;else{var csrf=browserCookie(csrfCookieName);if(csrf)headers['x-csrf-token']=csrf;}return fetch(API+'&action=notice.attachment.upload',{method:'POST',headers:headers,body:body,credentials:'same-origin'}).then(function(response){return response.json().catch(function(){return{};}).then(function(result){if(!response.ok){var failure=new Error(result.error||'No se pudo importar el archivo.');failure.httpStatus=response.status;failure.code=result.code||'';throw failure;}return result;});});}
  function setBusy(form,busy,message){var submit=form&&form.querySelector('button[type=submit]');if(!form||!submit)return;if(!submit.dataset.defaultLabel)submit.dataset.defaultLabel=submit.textContent;form.setAttribute('aria-busy',busy?'true':'false');submit.disabled=Boolean(busy);submit.textContent=busy?(message||'Procesando…'):submit.dataset.defaultLabel;}
  function clearBearer(){sessionStorage.removeItem(tokenKey);accessToken='';if(authMode==='bearer')authMode='';}
  function showLogin(message,error){document.getElementById('authCard').hidden=false;document.getElementById('authMethods').hidden=false;document.getElementById('passwordChangeCard').hidden=true;document.getElementById('manageApp').hidden=true;if(message!==undefined)authStatus(message,error);}
  function showPasswordChange(message){document.getElementById('authCard').hidden=false;document.getElementById('authMethods').hidden=true;document.getElementById('passwordChangeCard').hidden=false;document.getElementById('manageApp').hidden=true;authStatus(message||'Crea una contraseña personal para continuar.');var input=document.getElementById('newPassword');input.value='';document.getElementById('confirmPassword').value='';setTimeout(function(){input.focus();},0);}
  function card(eyebrow,title,detail){var item=el('article','manage-item'),copy=el('div');copy.appendChild(el('span','',eyebrow));copy.appendChild(el('strong','',title));if(detail)copy.appendChild(el('small','',detail));item.appendChild(copy);return item;}
  function empty(target,text){target.replaceChildren(el('p','empty',text));}
  function field(form,name){return form.elements.namedItem(name);}
  function setField(form,name,value){var input=field(form,name);if(!input)return;if(input.type==='checkbox')input.checked=Boolean(value);else input.value=value==null?'':String(value);}
  function localDateTime(value){var text=String(value||'');if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(text))return text.slice(0,16);return text;}
  function normalizedSubject(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
  function simpleStatus(value){return value==='published'?'Publicado':value==='archived'?'Archivado':value==='active'?'Activo':'Borrador';}
  function simplePriority(value){return value==='urgent'?'Urgente':value==='important'?'Importante':'Normal';}
  function taskValue(task,camel,snake){return task[camel]!==undefined?task[camel]:task[snake];}
  function linkedTaskIdForNotice(notice){return String(taskValue(notice||{},'linkedTaskId','linked_task_id')||'').trim();}
  function linkedNoticeForTask(task){var taskId=String(task&&task.id||'');return(state&&state.notices||[]).find(function(notice){return linkedTaskIdForNotice(notice)===taskId;})||null;}
  function taskNoticeEnabled(task){var direct=taskValue(task||{},'noticeEnabled','notice_enabled');if(direct!==undefined)return direct===true||direct===1||direct==='1';var linked=linkedNoticeForTask(task);return Boolean(linked&&linked.status!=='archived');}
  function naturalCompare(left,right){return String(left||'').localeCompare(String(right||''),'es',{numeric:true,sensitivity:'base'});}
  function formatDateTime(value){var raw=String(value||'').trim(),date=raw?new Date(raw):null;if(!date||Number.isNaN(date.getTime()))return raw;try{return new Intl.DateTimeFormat('es-PY',{dateStyle:'medium',timeStyle:'short'}).format(date);}catch(error){return raw;}}
  function preferredScrollBehavior(){return window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';}
  function normalizeE164(value){var raw=String(value||'').normalize('NFKC').trim();if(raw.indexOf('00')===0)raw='+'+raw.slice(2);var canonical=raw.replace(/[\s().-]/g,'');return /^\+[1-9][0-9]{7,14}$/.test(canonical)?canonical:'';}
  function profileWhatsapp(){return normalizeE164(state&&state.profile&&state.profile.whatsapp);}
  function updateAccessRequest(classInfo){var link=document.getElementById('requestAccessLink'),help=document.getElementById('requestAccessHelp');if(!link||!help)return;var info=classInfo||{},className=info.name||classSlug.toUpperCase(),support=normalizeE164(info.supportWhatsapp),message='Hola, soy delegado/a y quiero solicitar acceso al panel Med Nykuto de '+className+'.';if(support){link.href='https://wa.me/'+support.slice(1)+'?text='+encodeURIComponent(message);link.target='_blank';link.rel='noopener noreferrer';help.textContent='La solicitud se abrirá en WhatsApp.';}else{link.href='mailto:contact@nykuto.com?subject='+encodeURIComponent('Solicitud de acceso · '+className)+'&body='+encodeURIComponent(message);link.removeAttribute('target');link.removeAttribute('rel');help.textContent='La solicitud se preparará por correo electrónico.';}}
  function loadLoginSupport(){return request('public',{bearer:false}).then(function(data){updateAccessRequest(data.class||{});}).catch(function(){updateAccessRequest({name:classSlug.toUpperCase()});});}
  function subjectIdForCourse(course){var key=normalizedSubject(course),exact=(state.subjects||[]).find(function(subject){return normalizedSubject(subject.name)===key;});if(exact)return exact.id;var candidates=(state.subjects||[]).filter(function(subject){var subjectKey=normalizedSubject(subject.name);return key&&subjectKey&&(subjectKey.indexOf(key)===0||key.indexOf(subjectKey)===0);});return candidates.length===1?candidates[0].id:'';}
  function refreshTaskDateOptions(selectedValue){var select=document.getElementById('taskSuggestedDate'),course=document.getElementById('taskCourseInput').value.trim(),subjectId=subjectIdForCourse(course),courseKey=normalizedSubject(course),dates=(state&&state.upcomingDates||[]).filter(function(item){if(subjectId&&item.subjectId)return item.subjectId===subjectId;return courseKey&&normalizedSubject(item.subject)===courseKey;}).sort(function(left,right){return String(left.startsAt||'').localeCompare(String(right.startsAt||''));});select.replaceChildren();var placeholder=el('option','',course?(dates.length?'Selecciona una de las próximas clases':'No hay próximas clases configuradas'):'Selecciona primero una materia');placeholder.value='';select.appendChild(placeholder);dates.forEach(function(item){var slot=(state.scheduleSlots||[]).find(function(candidate){return candidate.id===item.slotId;}),option=el('option','',item.label+(slot&&slot.label?' · '+slot.label:''));option.value=localDateTime(item.startsAt);option.dataset.dueLabel=item.label||'';select.appendChild(option);});var match=localDateTime(selectedValue||document.getElementById('taskDueAtInput').value);if(match&&Array.prototype.some.call(select.options,function(option){return option.value===match;}))select.value=match;select.disabled=!course||!dates.length;}
  function bindTaskDateSuggestions(){var course=document.getElementById('taskCourseInput'),suggested=document.getElementById('taskSuggestedDate'),dueAt=document.getElementById('taskDueAtInput'),dueLabel=field(document.getElementById('taskForm'),'dueLabel');function update(){refreshTaskDateOptions(dueAt.value);}course.addEventListener('input',update);course.addEventListener('change',update);dueAt.addEventListener('change',function(){refreshTaskDateOptions(dueAt.value);});suggested.addEventListener('change',function(){if(!suggested.value)return;dueAt.value=localDateTime(suggested.value);var option=suggested.options[suggested.selectedIndex];if(option&&option.dataset.dueLabel)dueLabel.value=option.dataset.dueLabel;dueAt.dispatchEvent(new Event('change',{bubbles:true}));});document.getElementById('taskForm').addEventListener('reset',function(){setTimeout(function(){refreshTaskDateOptions('');},0);});}
  function updateTaskNoticeUi(){var form=document.getElementById('taskForm'),toggle=document.getElementById('taskAddToNotices'),options=document.getElementById('taskNoticeOptions'),message=document.getElementById('taskNoticeStatus'),submit=form&&form.querySelector('button[type=submit]');if(!form||!toggle||!options||!message||!submit)return;var enabled=toggle.checked,statusValue=field(form,'status').value,priority=field(form,'noticePriority'),push=field(form,'noticePushMode'),editing=form.dataset.editing==='true',hadLinked=form.dataset.hadLinkedNotice==='true',pushAvailable=enabled&&priority.value!=='normal';options.hidden=!enabled;push.closest('label').hidden=!pushAvailable;if(!pushAvailable)push.checked=false;toggle.setAttribute('aria-expanded',enabled?'true':'false');if(enabled){message.textContent=statusValue==='published'?'La tarea y el aviso serán visibles. Si modificas uno, se actualizarán juntos.':statusValue==='archived'?'La tarea y su aviso enlazado quedarán archivados.':'La tarea y el aviso quedarán en borrador hasta que los publiques.';}else message.textContent=hadLinked?'Al guardar, el aviso enlazado se archivará sin borrar la tarea.':'El aviso solo se creará si activas esta opción.';submit.textContent=enabled?(editing?'Actualizar tarea y aviso':'Guardar tarea y aviso'):(editing?'Actualizar tarea':'Guardar tarea');submit.dataset.defaultLabel=submit.textContent;}
  function bindTaskNoticeOptions(){var form=document.getElementById('taskForm'),toggle=document.getElementById('taskAddToNotices'),statusInput=document.getElementById('taskStatusInput'),priority=field(form,'noticePriority');toggle.addEventListener('change',updateTaskNoticeUi);statusInput.addEventListener('change',updateTaskNoticeUi);priority.addEventListener('change',updateTaskNoticeUi);form.addEventListener('reset',function(){setTimeout(function(){delete form.dataset.hadLinkedNotice;updateTaskNoticeUi();},0);});updateTaskNoticeUi();}
  function bindPasswordToggles(root){(root||document).querySelectorAll('[data-password-toggle]').forEach(function(button){if(button.dataset.bound==='true')return;var input=document.getElementById(button.getAttribute('aria-controls'));if(!input)return;button.dataset.bound='true';button.addEventListener('click',function(){var reveal=input.type==='password';input.type=reveal?'text':'password';button.setAttribute('aria-pressed',reveal?'true':'false');var action=reveal?'Ocultar':'Mostrar',label=(input.id==='accessToken'?' token':input.id==='inviteToken'?' código de invitación':' contraseña');button.setAttribute('aria-label',action+label);button.title=action+label;var hidden=button.querySelector('.sr-only');if(hidden)hidden.textContent=action+label;input.focus({preventScroll:true});});});}
  function showForm(tab,formId,values,label){var tabButton=document.querySelector('[data-manage-tab="'+tab+'"]'),form=document.getElementById(formId);if(tabButton)tabButton.click();Object.keys(values).forEach(function(name){setField(form,name,values[name]);});if(formId==='taskForm'){refreshTaskDateOptions(values.dueAt);form.dataset.hadLinkedNotice=values.linkedNoticeId?'true':'false';}if(formId==='noticeForm'){clearNoticeFileSelection();showNoticeAttachment(values);}var advanced=field(form,'id');if(advanced&&advanced.value){var details=advanced.closest('details');if(details)details.open=true;}if(formId==='classForm'){field(form,'slug').readOnly=true;form.dataset.originalStatus=values.status||'active';var archiveOption=field(form,'status').querySelector('option[value="archived"]');if(archiveOption)archiveOption.disabled=values.slug==='s4-e';document.getElementById('classFormTitle').textContent='Modificar clase';}var submit=form.querySelector('button[type=submit]');if(submit){if(!submit.dataset.defaultLabel)submit.dataset.defaultLabel=submit.textContent;submit.textContent=label;}form.dataset.editing='true';if(formId==='taskForm')updateTaskNoticeUi();form.scrollIntoView({behavior:preferredScrollBehavior(),block:'start'});var first=form.querySelector('input:not([type=hidden]),select,textarea');if(first)first.focus({preventScroll:true});}
  function clearEditMode(form){delete form.dataset.editing;delete form.dataset.hadLinkedNotice;var submit=form.querySelector('button[type=submit]');if(submit&&submit.dataset.defaultLabel)submit.textContent=submit.dataset.defaultLabel;if(form.getAttribute('id')==='classForm'){delete form.dataset.originalStatus;field(form,'slug').readOnly=false;field(form,'slug').removeAttribute('readonly');var archiveOption=field(form,'status').querySelector('option[value="archived"]');if(archiveOption)archiveOption.disabled=false;document.getElementById('classFormTitle').textContent='Nueva clase';}form.querySelectorAll('details.advanced-fields').forEach(function(details){details.open=false;});if(form.getAttribute('id')==='taskForm')updateTaskNoticeUi();}
  function showNewForm(tab,formId,values){var tabButton=document.querySelector('[data-manage-tab="'+tab+'"]'),form=document.getElementById(formId);form.reset();clearEditMode(form);Object.keys(values||{}).forEach(function(name){setField(form,name,values[name]);});if(tabButton)tabButton.click();if(formId==='taskForm'){refreshTaskDateOptions('');updateTaskNoticeUi();}if(formId==='noticeForm'){clearNoticeFileSelection();showNoticeAttachment({});}form.scrollIntoView({behavior:preferredScrollBehavior(),block:'start'});var first=form.querySelector('input:not([type=hidden]),select,textarea');if(first)first.focus({preventScroll:true});}
  function actionButtons(edit,archive,isArchived){var actions=el('div','manage-item-actions'),editButton=el('button','','Modificar');editButton.type='button';editButton.addEventListener('click',edit);actions.appendChild(editButton);if(!isArchived){var archiveButton=el('button','archive-action','Archivar');archiveButton.type='button';archiveButton.addEventListener('click',archive);actions.appendChild(archiveButton);}return actions;}
  function copyText(value){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(value);return new Promise(function(resolve,reject){var input=document.createElement('textarea');input.value=value;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();try{if(!document.execCommand('copy'))throw new Error('copy_failed');resolve();}catch(error){reject(error);}finally{input.remove();}});}
  function populateLookups(){var subjects=[],seen={};(state.subjects||[]).concat((state.tasks||[]).map(function(item){return {name:item.course};}),(state.notices||[]).map(function(item){return {name:item.course};}),(state.activities||[]).map(function(item){return {name:item.course};}),(state.files||[]).map(function(item){return {name:item.course};}),(state.dates||[]).map(function(item){return {name:item.course};})).forEach(function(subject){var name=String(subject.name||'').trim(),key=name.toLowerCase();if(!name||seen[key])return;seen[key]=true;subjects.push(name);});subjects.sort(function(left,right){return left.localeCompare(right,'es');});var subjectOptions=document.getElementById('subjectOptions');subjectOptions.replaceChildren();subjects.forEach(function(name){var option=el('option');option.value=name;subjectOptions.appendChild(option);});refreshTaskDateOptions(document.getElementById('taskDueAtInput').value);var activitySelect=document.getElementById('groupActivitySelect'),selected=activitySelect.value;activitySelect.replaceChildren();var placeholder=el('option','','Selecciona una actividad');placeholder.value='';activitySelect.appendChild(placeholder);(state.activities||[]).forEach(function(activity){var option=el('option','',activity.title+(activityLocked(activity)?' · cerrada':activity.status==='archived'?' · archivada':''));option.value=activity.id;option.disabled=activityLocked(activity)||activity.status==='archived';activitySelect.appendChild(option);});if(Array.prototype.some.call(activitySelect.options,function(option){return option.value===selected&&!option.disabled;}))activitySelect.value=selected;}
  function taskFields(task){var dueLabel=taskValue(task,'dueLabel','due_label')||'',dueAt=taskValue(task,'dueAt','due_at')||'',attachmentUrl=taskValue(task,'attachmentUrl','attachment_url')||'',attachmentTitle=taskValue(task,'attachmentTitle','attachment_title')||'',linked=linkedNoticeForTask(task),enabled=taskNoticeEnabled(task),priority=linked&&linked.priority||taskValue(task,'noticePriority','notice_priority')||'normal',pushMode=linked?taskValue(linked,'pushMode','push_mode'):taskValue(task,'noticePushMode','notice_push_mode'),linkedNoticeId=linked&&linked.id||taskValue(task,'linkedNoticeId','linked_notice_id')||'';return{id:task.id,course:task.course||'',title:task.title,description:task.description||'',dueLabel:dueLabel,dueAt:localDateTime(dueAt),attachmentUrl:attachmentUrl,attachmentTitle:attachmentTitle,status:task.status,addToNotices:enabled,noticePriority:priority,noticePushMode:Boolean(pushMode),linkedNoticeId:linkedNoticeId};}
  function taskNoticeLabel(task,enabled){if(!enabled)return'Sin aviso';if(task.status==='published')return'Aviso visible ✓';if(task.status==='archived')return'Aviso archivado';return'Aviso en borrador';}
  function editTask(task){showForm('tasks','taskForm',taskFields(task),'Actualizar tarea');}
  function editTaskAndEnableNotice(task){editTask(task);var toggle=document.getElementById('taskAddToNotices');toggle.checked=true;updateTaskNoticeUi();setTimeout(function(){toggle.focus({preventScroll:true});},0);}
  function archiveTask(task){var values=taskFields(task);if(!confirm('¿Archivar la tarea «'+task.title+'»?'))return;values.action='task.upsert';values.dueAt=taskValue(task,'dueAt','due_at')||'';values.status='archived';mutate(values);}
  function noticeFields(notice){return{id:notice.id,course:taskValue(notice,'course','course')||'',priority:notice.priority,title:notice.title,body:notice.body||'',imageUrl:taskValue(notice,'imageUrl','image_url')||'',imageAlt:taskValue(notice,'imageAlt','image_alt')||'',attachmentUploadId:taskValue(notice,'attachmentUploadId','attachment_upload_id')||'',attachmentUrl:taskValue(notice,'attachmentUrl','attachment_url')||'',attachmentTitle:taskValue(notice,'attachmentTitle','attachment_title')||'',attachmentMimeType:taskValue(notice,'attachmentMimeType','attachment_mime_type')||'',attachmentSizeBytes:Number(taskValue(notice,'attachmentSizeBytes','attachment_size_bytes'))||0,status:notice.status,pushMode:Boolean(taskValue(notice,'pushMode','push_mode'))};}
  function formatFileSize(bytes){var value=Number(bytes)||0;if(!value)return'';if(value<1024*1024)return Math.max(1,Math.round(value/1024))+' KB';return(value/(1024*1024)).toFixed(value<10*1024*1024?1:0)+' MB';}
  function clearNoticeObjectUrl(){if(noticeObjectUrl){URL.revokeObjectURL(noticeObjectUrl);noticeObjectUrl='';}}
  function clearNoticeFileSelection(){var input=document.getElementById('noticeAttachmentFile');if(!input)return;input.value='';input.setCustomValidity('');}
  function showNoticeAttachment(values,localFile){var preview=document.getElementById('noticeAttachmentPreview'),remove=document.getElementById('noticeAttachmentRemove'),uploadId=document.getElementById('noticeAttachmentUploadId'),titleInput=document.getElementById('noticeAttachmentTitle');clearNoticeObjectUrl();preview.replaceChildren();if(!localFile){noticeAttachmentBaseline={attachmentUploadId:values.attachmentUploadId||'',attachmentUrl:values.attachmentUrl||'',attachmentTitle:values.attachmentTitle||'',attachmentMimeType:values.attachmentMimeType||'',attachmentSizeBytes:Number(values.attachmentSizeBytes)||0};uploadId.value=noticeAttachmentBaseline.attachmentUploadId;titleInput.value=noticeAttachmentBaseline.attachmentTitle;}var url=String(values.attachmentUrl||''),title=String(values.attachmentTitle||(localFile&&localFile.name)||'Archivo del aviso'),mime=String(values.attachmentMimeType||(localFile&&localFile.type)||''),size=Number(values.attachmentSizeBytes||(localFile&&localFile.size)||0);if(localFile){noticeObjectUrl=URL.createObjectURL(localFile);url=noticeObjectUrl;}if(!url&&!uploadId.value){preview.hidden=true;remove.hidden=true;return;}var copy=el('span','notice-upload-copy'),strong=el('strong','',title),small=el('small','',(mime.indexOf('application/pdf')===0?'PDF':'Imagen')+(size?' · '+formatFileSize(size):'')),badge=el('span','notice-upload-file-icon',mime.indexOf('application/pdf')===0?'PDF':'IMG');copy.appendChild(strong);copy.appendChild(small);if(mime.indexOf('image/')===0&&url){var image=el('img','notice-upload-thumb');image.src=url;image.alt='';image.addEventListener('error',function(){image.replaceWith(badge);});preview.appendChild(image);}else preview.appendChild(badge);preview.appendChild(copy);if(url&&!localFile){var open=el('a','','Abrir');open.href=url;open.target='_blank';open.rel='noopener noreferrer';open.setAttribute('aria-label','Abrir '+title);preview.appendChild(open);}preview.hidden=false;remove.hidden=false;}
  function updateNoticeUploadPolicy(){var policy=state&&state.uploadPolicy||{},enabled=Boolean(policy.enabled),input=document.getElementById('noticeAttachmentFile'),field=document.getElementById('noticeUploadField'),help=document.getElementById('noticeAttachmentHelp'),picker=field&&field.querySelector('.notice-file-picker>span'),maximum=Number(policy.maxBytes)||15*1024*1024;input.disabled=!enabled;field.classList.toggle('is-unavailable',!enabled);if(enabled){help.textContent='Una sola foto o un solo PDF, máximo '+formatFileSize(maximum)+'.';if(picker)picker.textContent='Elegir de la galería o de los archivos';}else{help.textContent='La importación directa está temporalmente indisponible. Mientras tanto, usa el enlace de imagen de abajo.';if(picker)picker.textContent='Importación temporalmente indisponible';}}
  function editNotice(notice){var linkedTaskId=linkedTaskIdForNotice(notice),task=linkedTaskId&&(state.tasks||[]).find(function(item){return item.id===linkedTaskId;});if(task){status('Este aviso se actualiza desde su tarea enlazada.');editTask(task);return;}showForm('notices','noticeForm',noticeFields(notice),'Actualizar aviso');}
  function archiveNotice(notice){var linkedTaskId=linkedTaskIdForNotice(notice),task=linkedTaskId&&(state.tasks||[]).find(function(item){return item.id===linkedTaskId;});if(task){status('Para retirar este aviso, abre la tarea y desmarca «Añadir también a Avisos».');editTask(task);return;}var values=noticeFields(notice);if(!confirm('¿Archivar el aviso «'+notice.title+'»?'))return;values.action='notice.upsert';values.status='archived';mutate(values);}
  function renderTasks(){var target=document.getElementById('taskList');target.replaceChildren();(state.tasks||[]).forEach(function(task){var values=taskFields(task),details=[values.dueLabel||'Sin fecha'];if(task.description)details.push(task.description);if(values.attachmentUrl)details.push('Archivo: '+(values.attachmentTitle||'Documento adjunto'));var item=card(simpleStatus(task.status)+' · '+(task.course||'General'),task.title,details.join(' · ')),copy=item.firstChild,badge=el('span','task-notice-badge'+(values.addToNotices&&task.status==='published'?' is-active':''),taskNoticeLabel(task,values.addToNotices)),actions=actionButtons(function(){editTask(task);},function(){archiveTask(task);},task.status==='archived');item.querySelector('span').classList.add('status-'+task.status);copy.appendChild(badge);if(!values.addToNotices&&task.status!=='archived'){var add=el('button','task-add-notice-action','Añadir a Avisos');add.type='button';add.addEventListener('click',function(){editTaskAndEnableNotice(task);});actions.insertBefore(add,actions.firstChild);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay tareas guardadas.');}
  function renderNotices(){var target=document.getElementById('noticeList');target.replaceChildren();(state.notices||[]).forEach(function(notice){var values=noticeFields(notice),linkedTaskId=linkedTaskIdForNotice(notice),linkedTask=linkedTaskId&&(state.tasks||[]).find(function(task){return task.id===linkedTaskId;}),item=card(simplePriority(notice.priority)+' · '+simpleStatus(notice.status)+(values.course?' · '+values.course:'')+(linkedTaskId?' · Vinculado a tarea':''),notice.title,notice.body),mediaUrl=values.imageUrl||(values.attachmentMimeType.indexOf('image/')===0?values.attachmentUrl:'');item.querySelector('span').classList.add('status-'+notice.status);if(mediaUrl){var preview=el('img','notice-preview');preview.src=mediaUrl;preview.alt=values.imageAlt||values.attachmentTitle||'';preview.loading='lazy';preview.referrerPolicy='no-referrer';item.firstChild.appendChild(preview);}if(values.attachmentUrl){var attachmentTitle=values.attachmentTitle||'Documento',attachment=el('a','notice-admin-attachment','Archivo: '+attachmentTitle+(values.attachmentSizeBytes?' · '+formatFileSize(values.attachmentSizeBytes):''));attachment.href=values.attachmentUrl;attachment.target='_blank';attachment.rel='noopener noreferrer';attachment.setAttribute('aria-label','Abrir '+attachmentTitle);item.firstChild.appendChild(attachment);}if(linkedTaskId){var linkedActions=el('div','manage-item-actions'),linkedButton=el('button','linked-task-action',linkedTask?'Modificar tarea':'Tarea no disponible');linkedButton.type='button';linkedButton.disabled=!linkedTask;if(linkedTask)linkedButton.addEventListener('click',function(){editTask(linkedTask);});linkedActions.appendChild(linkedButton);item.appendChild(linkedActions);}else item.appendChild(actionButtons(function(){editNotice(notice);},function(){archiveNotice(notice);},notice.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay avisos guardados.');}
  function memberName(member){return String(member.displayName||member.display_name||'').trim();}
  function memberLeader(member){return Boolean(member.isLeader||member.is_leader);}
  function groupActivityId(group){return group.activityId||group.activity_id;}
  function groupMembers(groupId){return (state.memberships||[]).filter(function(member){return (member.groupId||member.group_id)===groupId;});}
  function sortedGroupMembers(groupId){return groupMembers(groupId).slice().sort(function(left,right){var leaderDifference=Number(memberLeader(right))-Number(memberLeader(left));return leaderDifference||naturalCompare(memberName(left),memberName(right));});}
  function sortedActivityGroups(activityId){return (state.groups||[]).filter(function(group){return groupActivityId(group)===activityId;}).slice().sort(function(left,right){return naturalCompare(left.name,right.name);});}
  function activityLocked(activity){var closesAt=taskValue(activity,'closesAt','closes_at');return Boolean(activity.frozen||(closesAt&&new Date(closesAt).getTime()<=Date.now()));}
  function activityExportText(activity){var groups=sortedActivityGroups(activity.id),lines=['*'+activity.title+'*'];if(!groups.length)lines.push('Sin grupos creados.');groups.forEach(function(group){var members=sortedGroupMembers(group.id),responsible=members.find(memberLeader);lines.push('','*'+group.name+'* ('+members.length+'/'+group.capacity+')');if(group.topic)lines.push('Tema: '+group.topic);lines.push('Responsable: '+(responsible?memberName(responsible):'sin definir'));lines.push('Integrantes: '+(members.length?members.map(memberName).join(', '):'ninguno'));});return lines.join('\n');}
  function escapeHtml(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function openProfile(){var button=document.querySelector('[data-manage-tab="profile"]');if(button)button.click();var input=document.getElementById('profileWhatsapp');if(input)setTimeout(function(){input.focus({preventScroll:true});},0);}
  function printActivity(activity){var popup=window.open('','_blank');if(!popup){status('Permite ventanas emergentes para descargar el PDF.',true);return;}popup.opener=null;var title=escapeHtml(activity.title),text=escapeHtml(activityExportText(activity).replace(/\*/g,''));popup.document.write('<!doctype html><html lang="es"><head><meta charset="utf-8"><title>'+title+'</title><style>body{font:15px/1.5 system-ui;padding:30px;color:#111}h1{margin:0 0 18px;color:#075985;font-size:24px}pre{white-space:pre-wrap;font:inherit}</style></head><body><h1>'+title+'</h1><pre>'+text+'</pre></body></html>');popup.document.close();popup.focus();setTimeout(function(){popup.print();},250);}
  function activityFields(activity){return{id:activity.id,course:taskValue(activity,'course','course')||'',title:activity.title,capacity:activity.capacity||10,closesAt:localDateTime(taskValue(activity,'closesAt','closes_at')||''),status:activity.status};}
  function editActivity(activity){showForm('groups','activityForm',activityFields(activity),'Actualizar actividad');}
  function activityTools(activity,locked){var tools=el('div','activity-tools');tools.dataset.activityId=activity.id;var edit=el('button','edit-activity-action','Modificar actividad'),close=el('button','close-activity-action',locked?'Cambios cerrados':'Cerrar cambios'),copy=el('button','','Copiar lista'),whatsapp=profileWhatsapp(),send=el('button',whatsapp?'whatsapp-action':'profile-action',whatsapp?'Enviar a mi WhatsApp':'Añadir mi WhatsApp'),pdf=el('button','','Descargar PDF');edit.type='button';edit.addEventListener('click',function(){editActivity(activity);});[[close,'freeze'],[copy,'copy'],[send,'whatsapp'],[pdf,'pdf']].forEach(function(entry){entry[0].type='button';entry[0].dataset.activityId=activity.id;entry[0].dataset.groupAction=entry[1];});close.disabled=locked||activity.status==='archived';close.addEventListener('click',function(){if(confirm('¿Cerrar los cambios de «'+activity.title+'»? Los grupos y nombres se conservarán.'))mutate({action:'group.freeze',activityId:activity.id,frozen:true});});copy.addEventListener('click',function(){copyText(activityExportText(activity)).then(function(){status('Lista de «'+activity.title+'» copiada.');}).catch(function(){status('No se pudo copiar automáticamente.',true);});});if(whatsapp){send.addEventListener('click',function(){var url='https://wa.me/'+whatsapp.slice(1)+'?text='+encodeURIComponent(activityExportText(activity)),opened=window.open(url,'_blank');if(opened)opened.opener=null;else location.href=url;});}else send.addEventListener('click',openProfile);pdf.addEventListener('click',function(){printActivity(activity);});tools.appendChild(edit);tools.appendChild(close);tools.appendChild(copy);tools.appendChild(send);tools.appendChild(pdf);return tools;}
  function groupFields(group){return{id:group.id,activityId:groupActivityId(group),name:group.name,capacity:group.capacity||10};}
  function editGroup(group){showForm('groups','groupForm',groupFields(group),'Actualizar grupo');}
  function renderGroups(){var target=document.getElementById('groupList');target.replaceChildren();(state.activities||[]).slice().sort(function(left,right){return naturalCompare(left.title,right.title);}).forEach(function(activity){var locked=activityLocked(activity),closesAt=taskValue(activity,'closesAt','closes_at'),activityGroups=sortedActivityGroups(activity.id),course=taskValue(activity,'course','course')||'',activityItem=card(simpleStatus(activity.status)+(course?' · '+course:'')+(locked?' · Cambios cerrados':''),activity.title,'Máximo '+activity.capacity+' estudiantes por grupo'+(closesAt?' · cierre '+formatDateTime(closesAt):'')),wrap=el('div','activity-groups');activityItem.classList.add('activity-card');activityItem.dataset.activityId=activity.id;activityGroups.forEach(function(group){var members=sortedGroupMembers(group.id),groupDetail=members.length+'/'+group.capacity+' integrantes'+(group.topic?' · Tema: '+group.topic:''),groupItem=card(group.frozen||locked?'Cambios cerrados':'Cambios abiertos',group.name,groupDetail),memberList=el('div','member-list'),groupEdit=el('button','group-edit-action','Modificar grupo');groupItem.classList.add('group-card');members.forEach(function(member){var leader=memberLeader(member),name=memberName(member),chip=el('span','member-chip'+(leader?' member-leader':''),name+(leader?' · Responsable':'')),controls=el('span','member-controls'),move=el('select','member-move'),moveButton=el('button','','Mover'),remove=el('button','','Quitar');activityGroups.forEach(function(candidate){if(candidate.id===group.id)return;var option=el('option','',candidate.name);option.value=candidate.id;option.disabled=Boolean(candidate.frozen||groupMembers(candidate.id).length>=Math.min(candidate.capacity,activity.capacity));move.appendChild(option);});moveButton.type='button';moveButton.disabled=locked||!move.options.length;move.disabled=moveButton.disabled;moveButton.addEventListener('click',function(){if(move.value)mutate({action:'member.move',id:member.id,groupId:move.value});});remove.type='button';remove.disabled=locked;remove.addEventListener('click',function(){if(!confirm('¿Quitar a '+name+' del grupo?'))return;mutate({action:'member.remove',id:member.id});});controls.appendChild(move);controls.appendChild(moveButton);controls.appendChild(remove);chip.appendChild(controls);memberList.appendChild(chip);});groupItem.firstChild.appendChild(memberList);groupEdit.type='button';groupEdit.disabled=locked||Boolean(group.frozen);groupEdit.setAttribute('aria-label','Modificar '+group.name);groupEdit.addEventListener('click',function(){editGroup(group);});groupItem.appendChild(groupEdit);wrap.appendChild(groupItem);});activityItem.firstChild.appendChild(wrap);activityItem.appendChild(activityTools(activity,locked));target.appendChild(activityItem);});if(!target.children.length)empty(target,'No hay actividades de grupo.');}
  function fileFields(file){return{id:file.id,course:file.course||'',lessonDate:taskValue(file,'lessonDate','lesson_date')||'',title:file.title,url:file.url,fileType:taskValue(file,'fileType','file_type')||'',status:file.status};}
  function editFile(file){showForm('files','fileForm',fileFields(file),'Actualizar archivo');}
  function archiveFile(file){var values=fileFields(file);if(!confirm('¿Archivar el archivo «'+file.title+'»?'))return;values.action='file.upsert';values.status='archived';mutate(values);}
  function dateFields(date){return{id:date.id,course:taskValue(date,'course','course')||'',label:date.label,startsAt:localDateTime(taskValue(date,'startsAt','starts_at')||''),status:date.status};}
  function editDate(date){showForm('calendar','dateForm',dateFields(date),'Actualizar fecha');}
  function archiveDate(date){var values=dateFields(date);if(!confirm('¿Archivar la fecha «'+date.label+'»?'))return;values.action='date.upsert';values.startsAt=taskValue(date,'startsAt','starts_at')||'';values.status='archived';mutate(values);}
  function renderFiles(){var fileTarget=document.getElementById('fileList'),dateTarget=document.getElementById('dateList');fileTarget.replaceChildren();dateTarget.replaceChildren();(state.files||[]).forEach(function(file){var detail=[taskValue(file,'lessonDate','lesson_date')||'',taskValue(file,'fileType','file_type')||'Archivo'].filter(Boolean).join(' · '),item=card(simpleStatus(file.status)+' · '+(file.course||'General'),file.title,detail),actions=actionButtons(function(){editFile(file);},function(){archiveFile(file);},file.status==='archived'),open=el('a','','Abrir archivo');item.querySelector('span').classList.add('status-'+file.status);open.href=file.url;open.target='_blank';open.rel='noopener noreferrer';open.setAttribute('aria-label','Abrir '+file.title);actions.insertBefore(open,actions.firstChild);item.appendChild(actions);fileTarget.appendChild(item);});(state.dates||[]).forEach(function(date){var course=taskValue(date,'course','course')||'',startsAt=taskValue(date,'startsAt','starts_at')||'',item=card(simpleStatus(date.status)+' · '+(course||'Toda la clase'),date.label,formatDateTime(startsAt));item.querySelector('span').classList.add('status-'+date.status);item.appendChild(actionButtons(function(){editDate(date);},function(){archiveDate(date);},date.status==='archived'));dateTarget.appendChild(item);});if(!fileTarget.children.length)empty(fileTarget,'No hay archivos guardados.');if(!dateTarget.children.length)empty(dateTarget,'No hay fechas guardadas.');}
  function linkedSubjectId(item){var direct=taskValue(item,'subjectId','subject_id');if(direct&&(state.subjects||[]).some(function(subject){return subject.id===direct;}))return direct;return subjectIdForCourse(taskValue(item,'course','course')||'');}
  function cockpitCollection(subjectId){function linked(items){return(items||[]).filter(function(item){return linkedSubjectId(item)===subjectId;});}var activities=linked(state.activities),activityIds=activities.map(function(activity){return activity.id;});return{tasks:linked(state.tasks),notices:linked(state.notices),activities:activities,groups:(state.groups||[]).filter(function(group){return activityIds.includes(groupActivityId(group));}),files:linked(state.files),dates:linked(state.dates)};}
  function cockpitTotal(collection){return collection.tasks.length+collection.notices.length+collection.activities.length+collection.groups.length+collection.files.length+collection.dates.length;}
  function cockpitCount(label,count){var singular={tareas:'tarea',avisos:'aviso',grupos:'grupo',archivos:'archivo',fechas:'fecha'},chip=el('span','subject-count');chip.appendChild(el('b','',String(count)));chip.appendChild(document.createTextNode(' '+(count===1?singular[label]:label)));return chip;}
  function cockpitEntry(title,meta,edit,openUrl,disabled){var item=el('article','subject-entry'),copy=el('div'),actions=el('span','subject-entry-actions'),button=el('button','',disabled?'Cerrado':'Modificar');copy.appendChild(el('strong','',title));copy.appendChild(el('small','',meta));button.type='button';button.disabled=Boolean(disabled);button.setAttribute('aria-label',(disabled?'Cambios cerrados para ':'Modificar ')+title);button.addEventListener('click',edit);actions.appendChild(button);if(openUrl){var open=el('a','','Abrir');open.href=openUrl;open.target='_blank';open.rel='noopener noreferrer';open.setAttribute('aria-label','Abrir '+title);actions.insertBefore(open,button);}item.appendChild(copy);item.appendChild(actions);return item;}
  function cockpitSection(title,items,describe,edit,openUrl,isDisabled){if(!items.length)return null;var section=el('section','subject-entry-group'),heading=el('h4','',title),list=el('div','subject-entry-list');items.forEach(function(item){list.appendChild(cockpitEntry(item.title||item.label||item.name,describe(item),function(){edit(item);},openUrl?openUrl(item):'',isDisabled?isDisabled(item):false));});section.appendChild(heading);section.appendChild(list);return section;}
  function newSubjectActions(course){var actions=el('div','subject-new-actions'),definitions=[['Nueva tarea','tasks','taskForm'],['Nuevo aviso','notices','noticeForm'],['Nueva actividad','groups','activityForm'],['Nuevo archivo','files','fileForm'],['Nueva fecha','calendar','dateForm']];definitions.forEach(function(definition){var button=el('button','',definition[0]);button.type='button';button.addEventListener('click',function(){showNewForm(definition[1],definition[2],{course:course||''});});actions.appendChild(button);});return actions;}
  function subjectCockpitCard(subject,collection,isGeneral){var details=el('details','subject-dashboard'),summary=el('summary'),heading=el('span','subject-dashboard-heading'),name=el('strong','',subject.name),hint=el('small','',cockpitTotal(collection)+' elemento'+(cockpitTotal(collection)===1?'':'s')+' relacionado'+(cockpitTotal(collection)===1?'':'s')),counts=el('span','subject-counts'),body=el('div','subject-dashboard-body');details.dataset.subjectId=subject.id;heading.appendChild(name);heading.appendChild(hint);counts.appendChild(cockpitCount('tareas',collection.tasks.length));counts.appendChild(cockpitCount('avisos',collection.notices.length));counts.appendChild(cockpitCount('grupos',collection.groups.length));counts.appendChild(cockpitCount('archivos',collection.files.length));counts.appendChild(cockpitCount('fechas',collection.dates.length));summary.appendChild(heading);summary.appendChild(counts);body.appendChild(newSubjectActions(isGeneral?'':subject.name));var activitiesById={};collection.activities.forEach(function(item){activitiesById[item.id]=item;});var sections=[cockpitSection('Tareas',collection.tasks,function(item){var noticeLabel=taskNoticeLabel(item,taskNoticeEnabled(item));return simpleStatus(item.status)+' · '+(taskValue(item,'dueLabel','due_label')||'Sin fecha')+(noticeLabel==='Sin aviso'?'':' · '+noticeLabel);},editTask),cockpitSection('Avisos',collection.notices,function(item){return simplePriority(item.priority)+' · '+simpleStatus(item.status)+(linkedTaskIdForNotice(item)?' · Vinculado a tarea':'');},editNotice),cockpitSection('Actividades',collection.activities,function(item){return simpleStatus(item.status)+' · '+sortedActivityGroups(item.id).length+' grupo'+(sortedActivityGroups(item.id).length===1?'':'s');},editActivity),cockpitSection('Grupos',collection.groups,function(item){var activity=activitiesById[groupActivityId(item)];return (activity?activity.title+' · ':'')+groupMembers(item.id).length+'/'+item.capacity+' integrantes';},editGroup,null,function(item){var activity=activitiesById[groupActivityId(item)];return Boolean(item.frozen)||!activity||activityLocked(activity);}),cockpitSection('Archivos',collection.files,function(item){return simpleStatus(item.status)+' · '+(taskValue(item,'fileType','file_type')||'Enlace');},editFile,function(item){return item.url;}),cockpitSection('Fechas',collection.dates,function(item){return simpleStatus(item.status)+' · '+(formatDateTime(taskValue(item,'startsAt','starts_at'))||'Sin hora');},editDate)];sections.forEach(function(section){if(section)body.appendChild(section);});if(!cockpitTotal(collection))body.appendChild(el('p','subject-empty','Todavía no hay publicaciones relacionadas. Usa los botones de arriba para crear la primera.'));details.appendChild(summary);details.appendChild(body);return details;}
  function renderSubjectCockpit(){var target=document.getElementById('subjectCockpit');if(!target)return;target.replaceChildren();(state.subjects||[]).filter(function(subject){return subject.status!=='archived';}).slice().sort(function(left,right){return Number(left.order||0)-Number(right.order||0)||naturalCompare(left.name,right.name);}).forEach(function(subject){target.appendChild(subjectCockpitCard(subject,cockpitCollection(subject.id),false));});var general=cockpitCollection('');target.appendChild(subjectCockpitCard({id:'general',name:'General · toda la clase'},general,true));}
  function renderProfile(){var form=document.getElementById('profileForm'),profile=state.profile||{},profileStatus=document.getElementById('profileStatus');setField(form,'name',profile.name||state.actor.name||'');setField(form,'email',profile.email||'');setField(form,'whatsapp',profile.whatsapp||'');profileStatus.textContent=profile.whatsappFormatVerifiedAt&&profile.whatsapp?'Formato del número verificado.':'';}
  function renderInvites(){var target=document.getElementById('inviteList');if(!target)return;target.replaceChildren();(state.invites||[]).forEach(function(invite){var active=!invite.revoked_at&&!invite.claimed_at&&new Date(invite.expires_at).getTime()>Date.now(),label=invite.claimed_at?'UTILIZADA':invite.revoked_at?'REVOCADA':active?'ACTIVA':'CADUCADA',item=card(label,invite.label,'Vence: '+invite.expires_at),actions=el('div','manage-item-actions');if(active){var revoke=el('button','','Revocar invitación');revoke.type='button';revoke.addEventListener('click',function(){if(confirm('¿Revocar esta invitación?'))mutate({action:'invite.revoke',id:invite.id});});actions.appendChild(revoke);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay invitaciones recientes.');}
  function openPasswordReset(editor){var dialog=document.getElementById('resetPasswordDialog'),form=document.getElementById('resetPasswordForm');resetEditorId=editor.id;setField(form,'id',editor.id);setField(form,'temporaryPassword','');setField(form,'hours','24');document.getElementById('resetPasswordEditor').textContent='La nueva contraseña temporal de '+editor.name+' caducará y deberá cambiarse al entrar.';if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');setTimeout(function(){field(form,'temporaryPassword').focus();},0);}
  function renderEditors(){var target=document.getElementById('editorList');target.replaceChildren();(state.editors||[]).forEach(function(editor){var details=[];if(editor.email)details.push(editor.email);details.push(editor.last_used_at?'Último uso: '+editor.last_used_at:'Todavía sin uso');if(editor.password_change_required)details.push('Cambio de contraseña pendiente');var item=card(editor.status.toUpperCase(),editor.name,details.join(' · ')),actions=el('div','manage-item-actions');if(editor.status==='active'){if(editor.email){var reset=el('button','','Restablecer contraseña');reset.type='button';reset.addEventListener('click',function(){openPasswordReset(editor);});actions.appendChild(reset);}var revoke=el('button','','Revocar');revoke.type='button';revoke.addEventListener('click',function(){if(confirm('¿Revocar el acceso de '+editor.name+'?'))mutate({action:'editor.revoke',id:editor.id});});actions.appendChild(revoke);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay editores activos.');}
  function renderSubjectsAdmin(){var target=document.getElementById('subjectListAdmin');if(!target)return;target.replaceChildren();(state.subjects||[]).forEach(function(subject){target.appendChild(card('ORDEN '+String(subject.order||0),subject.name,subject.id));});if(!target.children.length)empty(target,'No hay materias configuradas en esta clase.');}
  function classMutation(info,nextStatus){return {action:'class.upsert',id:info.id,slug:info.slug,name:info.name,semester:info.semester,group:info.group||'',theme:info.theme||'midnight-gold',driveUrl:info.driveUrl||'',supportWhatsapp:info.supportWhatsapp||'',status:nextStatus};}
  function renderClasses(){if(state.actor.role!=='owner')return;request('classes').then(function(data){var target=document.getElementById('classList');target.replaceChildren();(data.classes||[]).forEach(function(info){var archived=info.status==='archived',detail=info.slug+(info.supportWhatsapp?' · solicitudes: '+info.supportWhatsapp:''),item=card((archived?'ARCHIVADA':'ACTIVA')+' · SEMESTRE '+info.semester+(info.group?' · GRUPO '+info.group:''),info.name,detail),actions=el('div','manage-item-actions'),edit=el('button','','Modificar');item.querySelector('span').classList.add('status-'+info.status);edit.type='button';edit.addEventListener('click',function(){showForm('classes','classForm',{id:info.id,slug:info.slug,name:info.name,semester:info.semester,group:info.group||'',theme:info.theme||'midnight-gold',driveUrl:info.driveUrl||'',supportWhatsapp:info.supportWhatsapp||'',status:info.status},'Actualizar clase');});actions.appendChild(edit);if(archived){var reactivate=el('button','','Reactivar');reactivate.type='button';reactivate.addEventListener('click',function(){mutate(classMutation(info,'active'));});actions.appendChild(reactivate);}else{var open=el('a','','Abrir gestión'),space=el('a','','Ver clase');open.href='/gestion/'+encodeURIComponent(info.slug);space.href='/turma/'+encodeURIComponent(info.slug);actions.appendChild(open);actions.appendChild(space);if(info.slug!=='s4-e'){var archive=el('button','archive-action','Archivar');archive.type='button';archive.addEventListener('click',function(){if(confirm('¿Archivar la clase «'+info.name+'»? Su espacio dejará de estar disponible, pero sus datos se conservarán.'))mutate(classMutation(info,'archived'));});actions.appendChild(archive);}}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay clases registradas.');}).catch(function(error){status(error.message,true);});}
  function renderAudit(){if(state.actor.role!=='owner')return;request('audit').then(function(data){var target=document.getElementById('auditList');target.replaceChildren();(data.audit||[]).forEach(function(entry){target.appendChild(card(entry.actor_role.toUpperCase()+' · '+entry.action,entry.entity_type+' · '+entry.entity_id,entry.created_at));});if(!target.children.length)empty(target,'El registro está vacío.');}).catch(function(error){status(error.message,true);});}
  function render(){var info=state.class||{slug:classSlug,name:classSlug.toUpperCase()};document.getElementById('actorRole').textContent=state.actor.role==='owner'?'PROPIETARIO':'DELEGADO';document.getElementById('actorName').textContent=state.actor.name+' · '+(info.name||classSlug.toUpperCase());document.getElementById('manageClassLabel').textContent='Gestión · '+(info.name||classSlug.toUpperCase());document.getElementById('manageClassTitle').textContent='Panel de la clase · '+(info.name||classSlug.toUpperCase());document.getElementById('subjectClassLabel').textContent=(info.slug||classSlug).toUpperCase();document.querySelectorAll('[data-owner-only]').forEach(function(node){node.hidden=state.actor.role!=='owner';});updateAccessRequest(info);updateNoticeUploadPolicy();populateLookups();renderTasks();renderNotices();renderProfile();renderGroups();renderFiles();renderSubjectCockpit();renderInvites();renderEditors();renderSubjectsAdmin();renderClasses();renderAudit();}
  function load(){status('Cargando…');return request('admin').then(function(data){state=data;document.getElementById('authCard').hidden=true;document.getElementById('manageApp').hidden=false;status('Datos sincronizados.');authStatus('');render();var title=document.getElementById('manageClassTitle');setTimeout(function(){title.focus({preventScroll:true});},0);return data;}).catch(function(error){var terminal=error.httpStatus===400||error.httpStatus===401||error.httpStatus===403||error.httpStatus===404||error.httpStatus===410;if(error.code==='password_change_required'&&!accessToken){authMode='session';showPasswordChange(error.message);throw error;}if(state&&!terminal){status('Sincronización pendiente: los datos cargados y el formulario se mantienen.',true);return state;}if(terminal)clearBearer();showLogin(error.message,true);throw error;});}
  function mutate(data){status('Guardando…');return post(data,true).then(function(result){status('Cambio guardado y auditado.');if(data.action==='class.upsert'&&result.class&&result.class.slug===classSlug&&result.class.status==='archived'){sessionStorage.removeItem(tokenKey);location.href='/gestion/s4-e';return result;}return load().then(function(){return result;});}).catch(function(error){status(error.message,true);return null;});}
  function bindForm(id,reset){var form=document.getElementById(id);form.addEventListener('submit',function(event){event.preventDefault();if(form.getAttribute('aria-busy')==='true')return;var data=formData(form),submit=form.querySelector('button[type=submit]'),idleLabel=submit&&submit.textContent;setBusy(form,true,'Guardando…');mutate(data).then(function(result){if(result&&reset){form.reset();clearEditMode(form);}}).finally(function(){setBusy(form,false);if(id==='taskForm')updateTaskNoticeUi();else if(form.dataset.editing==='true'&&submit)submit.textContent=idleLabel;});});}
  function bindNoticeForm(){
    var form=document.getElementById('noticeForm'),fileInput=document.getElementById('noticeAttachmentFile'),remove=document.getElementById('noticeAttachmentRemove');
    fileInput.addEventListener('change',function(){
      fileInput.setCustomValidity('');
      var file=fileInput.files&&fileInput.files[0];
      if(!file){showNoticeAttachment(noticeAttachmentBaseline);return;}
      var maximum=Number(state&&state.uploadPolicy&&state.uploadPolicy.maxBytes)||15*1024*1024;
      if(file.size>maximum){
        fileInput.setCustomValidity('El archivo supera el máximo de '+formatFileSize(maximum)+'.');
        fileInput.reportValidity();
        fileInput.value='';
        showNoticeAttachment(noticeAttachmentBaseline);
        return;
      }
      showNoticeAttachment({attachmentTitle:file.name,attachmentMimeType:file.type,attachmentSizeBytes:file.size},file);
    });
    remove.addEventListener('click',function(){fileInput.value='';fileInput.setCustomValidity('');document.getElementById('noticeAttachmentUploadId').value='';document.getElementById('noticeAttachmentTitle').value='';showNoticeAttachment({});});
    form.addEventListener('reset',function(){setTimeout(function(){fileInput.value='';fileInput.setCustomValidity('');showNoticeAttachment({});},0);});
    form.addEventListener('submit',function(event){
      event.preventDefault();
      var file=fileInput.files&&fileInput.files[0],policy=state&&state.uploadPolicy||{},maximum=Number(policy.maxBytes)||15*1024*1024;
      if(file&&!policy.enabled){status('La importación directa todavía no está activada. Usa un enlace de imagen por ahora.',true);return;}
      if(file&&file.size>maximum){fileInput.setCustomValidity('El archivo supera el máximo de '+formatFileSize(maximum)+'.');fileInput.reportValidity();showNoticeAttachment(noticeAttachmentBaseline);return;}
      setBusy(form,true,file?'Importando archivo…':'Guardando…');
      fileInput.disabled=true;
      remove.disabled=true;
      status(file?'Importando el archivo de forma segura…':'Guardando…');
      (file?uploadNoticeFile(file):Promise.resolve(null)).then(function(uploaded){
        if(uploaded&&uploaded.attachment){
          var attachment=uploaded.attachment,uploadedValues={attachmentUploadId:attachment.uploadId,attachmentUrl:attachment.attachmentUrl||'',attachmentTitle:attachment.title||attachment.originalName||file.name,attachmentMimeType:attachment.mimeType||file.type,attachmentSizeBytes:Number(attachment.sizeBytes)||file.size};
          fileInput.value='';
          showNoticeAttachment(uploadedValues);
        }
        return mutate(formData(form));
      }).then(function(result){if(result){form.reset();clearEditMode(form);}}).catch(function(error){status(error.message,true);}).finally(function(){setBusy(form,false);updateNoticeUploadPolicy();remove.disabled=false;});
    });
  }
  function activateManageTab(button,focus){document.querySelectorAll('[data-manage-tab]').forEach(function(item){var active=item===button;item.setAttribute('aria-selected',active?'true':'false');item.tabIndex=active?0:-1;});document.querySelectorAll('[data-manage-panel]').forEach(function(panel){panel.hidden=panel.dataset.managePanel!==button.dataset.manageTab;});button.scrollIntoView({behavior:preferredScrollBehavior(),block:'nearest',inline:'nearest'});if(focus)button.focus({preventScroll:true});}
  function bindTabs(){var buttons=Array.prototype.slice.call(document.querySelectorAll('[data-manage-tab]'));buttons.forEach(function(button){button.tabIndex=button.getAttribute('aria-selected')==='true'?0:-1;button.addEventListener('click',function(){activateManageTab(button,false);});button.addEventListener('keydown',function(event){if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;var available=buttons.filter(function(item){return!item.hidden;}),current=available.indexOf(button),next=current;if(event.key==='Home')next=0;else if(event.key==='End')next=available.length-1;else next=(current+(event.key==='ArrowRight'?1:-1)+available.length)%available.length;event.preventDefault();activateManageTab(available[next],true);});});}
  function resetAuth(message){state=null;clearBearer();authMode='';document.getElementById('loginPassword').value='';document.getElementById('accessToken').value='';showLogin(message||'Sesión cerrada correctamente.',false);setTimeout(function(){document.getElementById('loginEmail').focus();},0);}
  function logout(){var buttons=document.querySelectorAll('#logoutButton,#passwordChangeLogout'),inManagement=!document.getElementById('manageApp').hidden;buttons.forEach(function(button){button.disabled=true;});if(inManagement)status('Cerrando sesión…');else authStatus('Cerrando sesión…');return post({action:'auth.logout'},{bearer:false,csrf:true}).then(function(){resetAuth('Sesión cerrada correctamente.');}).catch(function(error){if(inManagement)status(error.message,true);else authStatus(error.message,true);}).finally(function(){buttons.forEach(function(button){button.disabled=false;});});}
  function restoreSession(){authStatus('Comprobando sesión segura…');return request('session',{bearer:false}).then(function(data){authMode='session';if(data.passwordChangeRequired){showPasswordChange();return data;}return load();}).catch(function(error){if(error.code==='password_change_required'){authMode='session';showPasswordChange(error.message);return null;}if(error.httpStatus===401||error.httpStatus===403){showLogin('',false);return null;}showLogin(error.message,true);return null;});}
  function bindCredentialAuth(){
    var credentialForm=document.getElementById('credentialForm'),email=document.getElementById('loginEmail'),password=document.getElementById('loginPassword'),passwordForm=document.getElementById('passwordChangeForm'),newPassword=document.getElementById('newPassword'),confirmation=document.getElementById('confirmPassword');
    [email,password].forEach(function(input){input.setAttribute('aria-describedby','authStatus');input.addEventListener('input',function(){input.removeAttribute('aria-invalid');});});
    [newPassword,confirmation].forEach(function(input){input.setAttribute('aria-describedby','authStatus');input.addEventListener('input',function(){input.setCustomValidity('');input.removeAttribute('aria-invalid');});});
    credentialForm.addEventListener('submit',function(event){event.preventDefault();email.removeAttribute('aria-invalid');password.removeAttribute('aria-invalid');clearBearer();setBusy(credentialForm,true,'Verificando…');authStatus('Verificando la cuenta…');post({action:'auth.login',email:email.value.trim(),password:password.value},false).then(function(data){password.value='';authMode='session';if(data.passwordChangeRequired){showPasswordChange();return data;}return load();}).catch(function(error){password.value='';email.setAttribute('aria-invalid','true');password.setAttribute('aria-invalid','true');authStatus(error.message,true);password.focus();}).finally(function(){setBusy(credentialForm,false);});});
    passwordForm.addEventListener('submit',function(event){event.preventDefault();newPassword.setCustomValidity('');confirmation.setCustomValidity('');if(newPassword.value!==confirmation.value){confirmation.setCustomValidity('Las contraseñas no coinciden.');confirmation.setAttribute('aria-invalid','true');authStatus('Las contraseñas no coinciden.',true);confirmation.reportValidity();confirmation.focus();return;}setBusy(passwordForm,true,'Guardando…');authStatus('Protegiendo la nueva contraseña…');post({action:'auth.password.change',password:newPassword.value},true).then(function(){newPassword.value='';confirmation.value='';authMode='session';document.getElementById('passwordChangeCard').hidden=true;return load();}).catch(function(error){newPassword.value='';confirmation.value='';newPassword.setAttribute('aria-invalid','true');confirmation.setAttribute('aria-invalid','true');authStatus(error.message,true);newPassword.focus();}).finally(function(){setBusy(passwordForm,false);});});
    var passwordLogout=el('button','password-change-logout','Cerrar sesión');passwordLogout.id='passwordChangeLogout';passwordLogout.type='button';passwordLogout.addEventListener('click',logout);document.getElementById('passwordChangeCard').appendChild(passwordLogout);
  }
  function bindPasswordReset(){
    var dialog=el('dialog','credential-dialog'),form=el('form'),heading=el('h2','','Restablecer contraseña temporal'),description=el('p','','Med Nykuto no vuelve a mostrar ni registrar la contraseña después de guardarla.'),editor=el('p',''),id=el('input'),passwordGroup=el('div','field-group'),passwordLabel=el('label','', 'Nueva contraseña temporal'),passwordWrap=el('span','password-field'),password=el('input'),toggle=el('button','password-toggle'),eye=el('span','password-toggle-glyph','👁'),hidden=el('span','sr-only','Mostrar contraseña'),hoursLabel=el('label','', 'Validez en horas'),hours=el('input'),actions=el('div','credential-dialog-actions'),cancel=el('button','','Cancelar'),submit=el('button','','Guardar contraseña temporal');
    dialog.id='resetPasswordDialog';dialog.setAttribute('aria-labelledby','resetPasswordTitle');heading.id='resetPasswordTitle';editor.id='resetPasswordEditor';form.id='resetPasswordForm';id.type='hidden';id.name='id';password.id='resetTemporaryPassword';password.type='password';password.name='temporaryPassword';password.autocomplete='new-password';password.minLength=6;password.maxLength=128;password.required=true;passwordLabel.htmlFor=password.id;toggle.type='button';toggle.dataset.passwordToggle='';toggle.setAttribute('aria-controls',password.id);toggle.setAttribute('aria-pressed','false');toggle.setAttribute('aria-label','Mostrar contraseña');toggle.title='Mostrar contraseña';toggle.appendChild(eye);toggle.appendChild(hidden);passwordWrap.appendChild(password);passwordWrap.appendChild(toggle);passwordGroup.appendChild(passwordLabel);passwordGroup.appendChild(passwordWrap);hours.type='number';hours.name='hours';hours.min='1';hours.max='24';hours.value='24';cancel.type='button';submit.type='submit';hoursLabel.appendChild(hours);actions.appendChild(cancel);actions.appendChild(submit);form.appendChild(heading);form.appendChild(description);form.appendChild(editor);form.appendChild(id);form.appendChild(passwordGroup);form.appendChild(hoursLabel);form.appendChild(actions);dialog.appendChild(form);document.body.appendChild(dialog);bindPasswordToggles(dialog);
    cancel.addEventListener('click',function(){if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');});dialog.addEventListener('close',function(){resetEditorId='';password.value='';form.reset();hours.value='24';});
    form.addEventListener('submit',function(event){event.preventDefault();if(!resetEditorId||field(form,'id').value!==resetEditorId){status('No se pudo identificar al delegado.',true);return;}var data=formData(form);data.action='editor.password.reset';setBusy(form,true,'Guardando…');mutate(data).then(function(result){password.value='';if(!result)return;if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');status('Contraseña temporal actualizada. Debe comunicarse por un canal privado.');}).finally(function(){password.value='';setBusy(form,false);});});
  }
  function bindActions(){
    document.getElementById('logoutButton').addEventListener('click',logout);
  }
  function bindProfile(){var form=document.getElementById('profileForm'),whatsapp=document.getElementById('profileWhatsapp'),profileStatus=document.getElementById('profileStatus');whatsapp.addEventListener('input',function(){whatsapp.setCustomValidity('');profileStatus.textContent='';});form.addEventListener('submit',function(event){event.preventDefault();var raw=whatsapp.value.trim(),value=normalizeE164(raw);whatsapp.setCustomValidity('');if(raw&&!value){whatsapp.setCustomValidity('Usa el indicativo del país y un número válido, por ejemplo +595 981 234 567.');whatsapp.reportValidity();whatsapp.focus();return;}whatsapp.value=value;setBusy(form,true,'Guardando…');mutate({action:'profile.upsert',whatsapp:value}).then(function(result){if(result)profileStatus.textContent=value?'WhatsApp guardado correctamente.':'WhatsApp eliminado del perfil.';}).finally(function(){setBusy(form,false);});});}
  function init(){
    var classHome='/turma/'+encodeURIComponent(classSlug),manageTitle=document.getElementById('manageClassTitle'),passwordTitle=document.getElementById('passwordChangeTitle'),authStatusNode=document.getElementById('authStatus');document.getElementById('manageClassHome').href=classHome;document.getElementById('manageBackLink').href=classHome;document.getElementById('manageClassLabel').textContent='Gestión · '+classSlug.toUpperCase();document.getElementById('authClassSlug').textContent=classSlug.toUpperCase();document.getElementById('inviteLabel').value='Editor '+classSlug.toUpperCase();manageTitle.tabIndex=-1;passwordTitle.tabIndex=-1;authStatusNode.setAttribute('aria-atomic','true');updateAccessRequest({name:classSlug.toUpperCase()});loadLoginSupport();
    bindTabs();bindPasswordToggles(document);bindTaskDateSuggestions();bindTaskNoticeOptions();bindNoticeForm();['taskForm','activityForm','groupForm','fileForm','dateForm','subjectForm'].forEach(function(id){bindForm(id,true);});
    var classForm=document.getElementById('classForm'),classSupport=field(classForm,'supportWhatsapp');classSupport.addEventListener('input',function(){classSupport.setCustomValidity('');});classForm.addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget,data=formData(form),wasEditing=form.dataset.editing==='true',rawSupport=String(data.supportWhatsapp||'').trim(),canonicalSupport=normalizeE164(rawSupport);classSupport.setCustomValidity('');if(rawSupport&&!canonicalSupport){classSupport.setCustomValidity('Usa el indicativo del país y un número válido, por ejemplo +595 981 234 567.');classSupport.reportValidity();classSupport.focus();return;}classSupport.value=canonicalSupport;data.supportWhatsapp=canonicalSupport;if(data.status==='archived'&&form.dataset.originalStatus!=='archived'&&!confirm('¿Archivar esta clase? Su espacio dejará de estar disponible, pero sus datos se conservarán.'))return;mutate(data).then(function(result){if(!result||!result.class)return;var info=result.class,output=document.getElementById('classOutput');output.hidden=false;output.replaceChildren(document.createTextNode((wasEditing?'Clase actualizada: ':'Clase creada: ')+info.name+'. '));if(info.status==='active'){var manage=el('a','','Configurar ahora');manage.href='/gestion/'+encodeURIComponent(info.slug);output.appendChild(manage);}else output.appendChild(document.createTextNode('Está archivada; reactívala desde la lista para configurarla.'));form.reset();clearEditMode(form);});});
    document.getElementById('inviteForm').addEventListener('submit',function(event){event.preventDefault();var data=formData(event.currentTarget);mutate(data).then(function(result){if(!result||!result.inviteToken)return;var output=document.getElementById('inviteOutput'),heading=el('strong','','Invitación creada · se muestra una sola vez'),token=el('code','invite-token',result.inviteToken),expiry=el('small','invite-expiry','Vence: '+result.expiresAt),copy=el('button','','Copiar invitación');copy.type='button';copy.addEventListener('click',function(){copyText(result.inviteToken).then(function(){copy.textContent='Invitación copiada';status('Token de invitación copiado.');}).catch(function(){status('No se pudo copiar automáticamente. Selecciona el token y cópialo manualmente.',true);});});output.hidden=false;output.replaceChildren(heading,token,expiry,copy);});});
    document.getElementById('delegateAccountForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget,data=formData(form),temporaryPassword=field(form,'temporaryPassword');setBusy(form,true,'Creando…');mutate(data).then(function(result){temporaryPassword.value='';if(!result||!result.editor)return;var output=document.getElementById('accountOutput'),heading=el('strong','','Cuenta de delegado creada'),details=el('small','',result.editor.name+' · '+result.editor.email),expiry=el('small','account-expiry','Contraseña temporal válida hasta: '+result.temporaryExpiresAt);output.hidden=false;output.replaceChildren(heading,details,expiry);form.reset();field(form,'hours').value='24';}).finally(function(){temporaryPassword.value='';setBusy(form,false);});});
    bindCredentialAuth();bindPasswordReset();bindProfile();
    bindActions();
    document.getElementById('tokenForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget;accessToken=document.getElementById('accessToken').value.trim();authMode='bearer';sessionStorage.setItem(tokenKey,accessToken);setBusy(form,true,'Verificando…');load().then(function(){document.getElementById('accessToken').value='';}).catch(function(){}).finally(function(){setBusy(form,false);});});
    document.getElementById('claimForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget;authStatus('Activando…');setBusy(form,true,'Activando…');post({action:'invite.claim',inviteToken:document.getElementById('inviteToken').value.trim(),name:document.getElementById('inviteName').value.trim()},false).then(function(data){accessToken=data.editorToken;authMode='bearer';sessionStorage.setItem(tokenKey,accessToken);return load();}).catch(function(error){authStatus(error.message,true);}).finally(function(){setBusy(form,false);});});
    accessToken=sessionStorage.getItem(tokenKey)||'';if(accessToken){authMode='bearer';load().catch(function(){return restoreSession();});}else restoreSession();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
