(function(){
  'use strict';
  function currentClass(){var path=location.pathname.match(/^\/gestion\/([a-z0-9-]+)\/?$/i),query=new URLSearchParams(location.search).get('class'),raw=String((path&&path[1])||query||'').trim().toLowerCase();if(!raw)return's4-e';return/^[a-z0-9][a-z0-9-]{0,30}$/.test(raw)?raw:'invalid-class';}
  var classSlug=currentClass(),API='/api/class-hub?class='+encodeURIComponent(classSlug),tokenKey='med-nykuto-management-token-v471:'+classSlug,accessToken='',state=null;
  function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function status(message,error){var target=document.getElementById('manageStatus');target.textContent=message||'';target.style.color=error?'#fca5a5':'#86efac';}
  function authStatus(message,error){var target=document.getElementById('authStatus');target.textContent=message||'';target.style.color=error?'#fca5a5':'#86efac';}
  function request(resource,options){options=options||{};options.headers=Object.assign({'accept':'application/json'},options.headers||{},accessToken?{'authorization':'Bearer '+accessToken}:{});return fetch(API+(resource?'&resource='+encodeURIComponent(resource):''),options).then(function(response){return response.json().then(function(body){if(!response.ok){var failure=new Error(body.error||body.message||'No se pudo completar la operación.');failure.httpStatus=response.status;throw failure;}return body;});});}
  function formData(form){var data={};new FormData(form).forEach(function(value,key){data[key]=value;});form.querySelectorAll('input[type=checkbox]').forEach(function(input){data[input.name]=input.checked;});return data;}
  function post(data,withAuth){return request('',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});}
  function card(eyebrow,title,detail){var item=el('article','manage-item'),copy=el('div');copy.appendChild(el('span','',eyebrow));copy.appendChild(el('strong','',title));if(detail)copy.appendChild(el('small','',detail));item.appendChild(copy);return item;}
  function empty(target,text){target.replaceChildren(el('p','empty',text));}
  function field(form,name){return form.elements.namedItem(name);}
  function setField(form,name,value){var input=field(form,name);if(!input)return;if(input.type==='checkbox')input.checked=Boolean(value);else input.value=value==null?'':String(value);}
  function localDateTime(value){var text=String(value||'');if(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(text))return text.slice(0,16);return text;}
  function showForm(tab,formId,values,label){var tabButton=document.querySelector('[data-manage-tab="'+tab+'"]'),form=document.getElementById(formId);if(tabButton)tabButton.click();Object.keys(values).forEach(function(name){setField(form,name,values[name]);});var advanced=field(form,'id');if(advanced&&advanced.value){var details=advanced.closest('details');if(details)details.open=true;}if(formId==='classForm'){field(form,'slug').readOnly=true;form.dataset.originalStatus=values.status||'active';var archiveOption=field(form,'status').querySelector('option[value="archived"]');if(archiveOption)archiveOption.disabled=values.slug==='s4-e';document.getElementById('classFormTitle').textContent='Modificar turma';}var submit=form.querySelector('button[type=submit]');if(submit){if(!submit.dataset.defaultLabel)submit.dataset.defaultLabel=submit.textContent;submit.textContent=label;}form.dataset.editing='true';form.scrollIntoView({behavior:'smooth',block:'start'});var first=form.querySelector('input:not([type=hidden]),select,textarea');if(first)first.focus({preventScroll:true});}
  function clearEditMode(form){delete form.dataset.editing;var submit=form.querySelector('button[type=submit]');if(submit&&submit.dataset.defaultLabel)submit.textContent=submit.dataset.defaultLabel;if(form.id==='classForm'){delete form.dataset.originalStatus;field(form,'slug').readOnly=false;field(form,'slug').removeAttribute('readonly');var archiveOption=field(form,'status').querySelector('option[value="archived"]');if(archiveOption)archiveOption.disabled=false;document.getElementById('classFormTitle').textContent='Nueva turma';}form.querySelectorAll('details.advanced-fields').forEach(function(details){details.open=false;});}
  function actionButtons(edit,archive,isArchived){var actions=el('div','manage-item-actions'),editButton=el('button','','Modificar');editButton.type='button';editButton.addEventListener('click',edit);actions.appendChild(editButton);if(!isArchived){var archiveButton=el('button','archive-action','Archivar');archiveButton.type='button';archiveButton.addEventListener('click',archive);actions.appendChild(archiveButton);}return actions;}
  function copyText(value){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(value);return new Promise(function(resolve,reject){var input=document.createElement('textarea');input.value=value;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();try{if(!document.execCommand('copy'))throw new Error('copy_failed');resolve();}catch(error){reject(error);}finally{input.remove();}});}
  function populateLookups(){var subjects=[],seen={};(state.subjects||[]).concat((state.tasks||[]).map(function(item){return {name:item.course};}),(state.files||[]).map(function(item){return {name:item.course};})).forEach(function(subject){var name=String(subject.name||'').trim(),key=name.toLowerCase();if(!name||seen[key])return;seen[key]=true;subjects.push(name);});subjects.sort(function(left,right){return left.localeCompare(right,'es');});var subjectOptions=document.getElementById('subjectOptions');subjectOptions.replaceChildren();subjects.forEach(function(name){var option=el('option');option.value=name;subjectOptions.appendChild(option);});var activitySelect=document.getElementById('groupActivitySelect'),selected=activitySelect.value;activitySelect.replaceChildren();var placeholder=el('option','','Selecciona una actividad');placeholder.value='';activitySelect.appendChild(placeholder);(state.activities||[]).forEach(function(activity){var option=el('option','',activity.title+(activityLocked(activity)?' · cerrada':activity.status==='archived'?' · archivada':''));option.value=activity.id;option.disabled=activityLocked(activity)||activity.status==='archived';activitySelect.appendChild(option);});if(Array.prototype.some.call(activitySelect.options,function(option){return option.value===selected&&!option.disabled;}))activitySelect.value=selected;}
  function renderTasks(){var target=document.getElementById('taskList');target.replaceChildren();(state.tasks||[]).forEach(function(task){var item=card(task.status.toUpperCase()+' · '+task.course,task.title,(task.due_label||'Sin fecha visible')+(task.description?' · '+task.description:''));item.querySelector('span').classList.add('status-'+task.status);item.appendChild(actionButtons(function(){showForm('tasks','taskForm',{id:task.id,course:task.course,title:task.title,description:task.description,dueLabel:task.due_label,dueAt:localDateTime(task.due_at),status:task.status},'Actualizar tarea');},function(){if(confirm('¿Archivar la tarea «'+task.title+'»?'))mutate({action:'task.upsert',id:task.id,course:task.course,title:task.title,description:task.description||'',dueLabel:task.due_label||'',dueAt:task.due_at||'',status:'archived'});},task.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay tareas.');}
  function renderNotices(){var target=document.getElementById('noticeList');target.replaceChildren();(state.notices||[]).forEach(function(notice){var item=card(notice.priority.toUpperCase()+' · '+notice.status.toUpperCase(),notice.title,notice.body);item.querySelector('span').classList.add('status-'+notice.status);item.appendChild(actionButtons(function(){showForm('notices','noticeForm',{id:notice.id,priority:notice.priority,title:notice.title,body:notice.body,status:notice.status,pushMode:Boolean(notice.push_mode)},'Actualizar alerta');},function(){if(confirm('¿Archivar la alerta «'+notice.title+'»?'))mutate({action:'notice.upsert',id:notice.id,priority:notice.priority,title:notice.title,body:notice.body||'',status:'archived',pushMode:Boolean(notice.push_mode)});},notice.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay alertas.');}
  function groupMembers(groupId){return (state.memberships||[]).filter(function(member){return member.group_id===groupId;});}
  function activityLocked(activity){return Boolean(activity.frozen||(activity.closes_at&&new Date(activity.closes_at).getTime()<=Date.now()));}
  function renderGroups(){var target=document.getElementById('groupList');target.replaceChildren();(state.activities||[]).forEach(function(activity){var locked=activityLocked(activity),activityGroups=(state.groups||[]).filter(function(group){return group.activity_id===activity.id;}),activityItem=card((activity.status||'draft').toUpperCase()+(locked?' · COMPOSICIÓN FINAL':''),activity.title,'Capacidad general: '+activity.capacity+(activity.closes_at?' · cierre '+activity.closes_at:'') );var wrap=el('div');activityGroups.forEach(function(group){var groupItem=card(group.frozen||locked?'CONGELADO':'ABIERTO',group.name,groupMembers(group.id).length+'/'+group.capacity+' integrantes');var memberList=el('div','member-list');groupMembers(group.id).forEach(function(member){var chip=el('span','member-chip',member.display_name),controls=el('span','member-controls'),move=el('select','member-move'),moveButton=el('button','','Mover'),remove=el('button','','Quitar');activityGroups.forEach(function(candidate){if(candidate.id===group.id)return;var option=el('option','',candidate.name);option.value=candidate.id;option.disabled=Boolean(candidate.frozen||groupMembers(candidate.id).length>=Math.min(candidate.capacity,activity.capacity));move.appendChild(option);});moveButton.type='button';moveButton.disabled=locked||!move.options.length;move.disabled=moveButton.disabled;moveButton.addEventListener('click',function(){if(move.value)mutate({action:'member.move',id:member.id,groupId:move.value});});remove.type='button';remove.disabled=locked;remove.addEventListener('click',function(){if(!confirm('¿Quitar a '+member.display_name+' del grupo?'))return;mutate({action:'member.remove',id:member.id});});controls.appendChild(move);controls.appendChild(moveButton);controls.appendChild(remove);chip.appendChild(controls);memberList.appendChild(chip);});groupItem.firstChild.appendChild(memberList);wrap.appendChild(groupItem);});activityItem.firstChild.appendChild(wrap);target.appendChild(activityItem);});if(!target.children.length)empty(target,'No hay actividades de grupo.');}
  function renderFiles(){var target=document.getElementById('fileList');target.replaceChildren();(state.files||[]).forEach(function(file){var item=card(file.status.toUpperCase()+' · '+file.course,file.title,file.url);item.querySelector('span').classList.add('status-'+file.status);item.appendChild(actionButtons(function(){showForm('files','fileForm',{id:file.id,course:file.course,lessonDate:file.lesson_date,title:file.title,url:file.url,fileType:file.file_type,status:file.status},'Actualizar archivo');},function(){if(confirm('¿Archivar el archivo «'+file.title+'»?'))mutate({action:'file.upsert',id:file.id,course:file.course,lessonDate:file.lesson_date||'',title:file.title,url:file.url,fileType:file.file_type||'',status:'archived'});},file.status==='archived'));target.appendChild(item);});(state.dates||[]).forEach(function(date){var item=card(date.status.toUpperCase()+' · FECHA',date.label,date.starts_at);item.querySelector('span').classList.add('status-'+date.status);item.appendChild(actionButtons(function(){showForm('files','dateForm',{id:date.id,label:date.label,startsAt:localDateTime(date.starts_at),status:date.status},'Actualizar fecha');},function(){if(confirm('¿Archivar la fecha «'+date.label+'»?'))mutate({action:'date.upsert',id:date.id,label:date.label,startsAt:date.starts_at,status:'archived'});},date.status==='archived'));target.appendChild(item);});if(!target.children.length)empty(target,'No hay archivos ni fechas dinámicas.');}
  function renderInvites(){var target=document.getElementById('inviteList');if(!target)return;target.replaceChildren();(state.invites||[]).forEach(function(invite){var active=!invite.revoked_at&&!invite.claimed_at&&new Date(invite.expires_at).getTime()>Date.now(),label=invite.claimed_at?'UTILIZADA':invite.revoked_at?'REVOCADA':active?'ACTIVA':'CADUCADA',item=card(label,invite.label,'Vence: '+invite.expires_at),actions=el('div','manage-item-actions');if(active){var revoke=el('button','','Revocar invitación');revoke.type='button';revoke.addEventListener('click',function(){if(confirm('¿Revocar esta invitación?'))mutate({action:'invite.revoke',id:invite.id});});actions.appendChild(revoke);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay invitaciones recientes.');}
  function renderEditors(){var target=document.getElementById('editorList');target.replaceChildren();(state.editors||[]).forEach(function(editor){var item=card(editor.status.toUpperCase(),editor.name,editor.last_used_at?'Último uso: '+editor.last_used_at:'Todavía sin uso'),actions=el('div','manage-item-actions');if(editor.status==='active'){var revoke=el('button','','Revocar');revoke.type='button';revoke.addEventListener('click',function(){if(confirm('¿Revocar el acceso de '+editor.name+'?'))mutate({action:'editor.revoke',id:editor.id});});actions.appendChild(revoke);}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay editores activos.');}
  function renderSubjectsAdmin(){var target=document.getElementById('subjectListAdmin');if(!target)return;target.replaceChildren();(state.subjects||[]).forEach(function(subject){target.appendChild(card('ORDEN '+String(subject.order||0),subject.name,subject.id));});if(!target.children.length)empty(target,'No hay materias configuradas en esta turma.');}
  function classMutation(info,nextStatus){return {action:'class.upsert',id:info.id,slug:info.slug,name:info.name,semester:info.semester,group:info.group||'',theme:info.theme||'midnight-gold',driveUrl:info.driveUrl||'',status:nextStatus};}
  function renderClasses(){if(state.actor.role!=='owner')return;request('classes').then(function(data){var target=document.getElementById('classList');target.replaceChildren();(data.classes||[]).forEach(function(info){var archived=info.status==='archived',item=card((archived?'ARCHIVADA':'ACTIVA')+' · SEMESTRE '+info.semester+(info.group?' · GRUPO '+info.group:''),info.name,info.slug),actions=el('div','manage-item-actions'),edit=el('button','','Modificar');item.querySelector('span').classList.add('status-'+info.status);edit.type='button';edit.addEventListener('click',function(){showForm('classes','classForm',{id:info.id,slug:info.slug,name:info.name,semester:info.semester,group:info.group||'',theme:info.theme||'midnight-gold',driveUrl:info.driveUrl||'',status:info.status},'Actualizar turma');});actions.appendChild(edit);if(archived){var reactivate=el('button','','Reactivar');reactivate.type='button';reactivate.addEventListener('click',function(){mutate(classMutation(info,'active'));});actions.appendChild(reactivate);}else{var open=el('a','','Abrir gestión'),space=el('a','','Ver turma');open.href='/gestion/'+encodeURIComponent(info.slug);space.href='/turma/'+encodeURIComponent(info.slug);actions.appendChild(open);actions.appendChild(space);if(info.slug!=='s4-e'){var archive=el('button','archive-action','Archivar');archive.type='button';archive.addEventListener('click',function(){if(confirm('¿Archivar la turma «'+info.name+'»? Su espacio dejará de estar disponible, pero sus datos se conservarán.'))mutate(classMutation(info,'archived'));});actions.appendChild(archive);}}item.appendChild(actions);target.appendChild(item);});if(!target.children.length)empty(target,'No hay turmas registradas.');}).catch(function(error){status(error.message,true);});}
  function renderAudit(){if(state.actor.role!=='owner')return;request('audit').then(function(data){var target=document.getElementById('auditList');target.replaceChildren();(data.audit||[]).forEach(function(entry){target.appendChild(card(entry.actor_role.toUpperCase()+' · '+entry.action,entry.entity_type+' · '+entry.entity_id,entry.created_at));});if(!target.children.length)empty(target,'El registro está vacío.');}).catch(function(error){status(error.message,true);});}
  function render(){var info=state.class||{slug:classSlug,name:classSlug.toUpperCase()};document.getElementById('actorRole').textContent=state.actor.role==='owner'?'PROPIETARIO':'EDITOR';document.getElementById('actorName').textContent=state.actor.name+' · '+(info.name||classSlug.toUpperCase());document.getElementById('manageClassLabel').textContent='Gestión · '+(info.name||classSlug.toUpperCase());document.getElementById('manageClassTitle').textContent='Publicación · '+(info.name||classSlug.toUpperCase());document.getElementById('subjectClassLabel').textContent=(info.slug||classSlug).toUpperCase();document.querySelectorAll('[data-owner-only]').forEach(function(node){node.hidden=state.actor.role!=='owner';});populateLookups();renderTasks();renderNotices();renderGroups();renderFiles();renderInvites();renderEditors();renderSubjectsAdmin();renderClasses();renderAudit();}
  function load(){status('Cargando…');return request('admin').then(function(data){state=data;document.getElementById('authCard').hidden=true;document.getElementById('manageApp').hidden=false;status('Datos sincronizados.');render();}).catch(function(error){var terminal=error.httpStatus===400||error.httpStatus===401||error.httpStatus===403||error.httpStatus===404||error.httpStatus===410;if(state&&!terminal){status('Sincronización pendiente: los datos cargados y el formulario se mantienen.',true);return state;}if(terminal){sessionStorage.removeItem(tokenKey);accessToken='';}document.getElementById('authCard').hidden=false;document.getElementById('manageApp').hidden=true;authStatus(error.message,true);throw error;});}
  function mutate(data){status('Guardando…');return post(data,true).then(function(result){status('Cambio guardado y auditado.');if(data.action==='class.upsert'&&result.class&&result.class.slug===classSlug&&result.class.status==='archived'){sessionStorage.removeItem(tokenKey);location.href='/gestion/s4-e';return result;}return load().then(function(){return result;});}).catch(function(error){status(error.message,true);return null;});}
  function bindForm(id,reset){var form=document.getElementById(id);form.addEventListener('submit',function(event){event.preventDefault();var data=formData(form);mutate(data).then(function(result){if(result&&reset){form.reset();clearEditMode(form);}});});}
  function bindTabs(){document.querySelectorAll('[data-manage-tab]').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('[data-manage-tab]').forEach(function(item){item.setAttribute('aria-selected',item===button?'true':'false');});document.querySelectorAll('[data-manage-panel]').forEach(function(panel){panel.hidden=panel.dataset.managePanel!==button.dataset.manageTab;});});});}
  function exportText(){var lines=['*Grupos Med Nykuto*'];(state.activities||[]).forEach(function(activity){lines.push('', '*'+activity.title+'*');(state.groups||[]).filter(function(group){return group.activity_id===activity.id;}).forEach(function(group){var names=groupMembers(group.id).map(function(member){return member.display_name;});lines.push(group.name+' ('+names.length+'/'+group.capacity+'): '+(names.join(', ')||'sin integrantes'));});});return lines.join('\n');}
  function bindActions(){
    document.getElementById('freezeGroups').addEventListener('click',function(){var select=document.getElementById('groupActivitySelect'),id=select.value;if(!id){status('Selecciona primero una actividad abierta.',true);select.focus();return;}if(confirm('¿Congelar la actividad seleccionada? Los integrantes ya no podrán cambiar de grupo.'))mutate({action:'group.freeze',activityId:id,frozen:true});});
    document.getElementById('exportWhatsapp').addEventListener('click',function(){copyText(exportText()).then(function(){status('Resumen copiado para WhatsApp.');}).catch(function(){status('No se pudo copiar automáticamente.',true);});});
    document.getElementById('exportPdf').addEventListener('click',function(){var popup=window.open('','_blank');if(!popup){status('Permite ventanas emergentes para exportar el PDF.',true);return;}popup.opener=null;var text=exportText().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/\n/g,'<br>');popup.document.write('<!doctype html><html><head><title>Grupos Med Nykuto</title><style>body{font:16px/1.6 system-ui;padding:36px;color:#111}h1{color:#075985}</style></head><body><h1>Grupos Med Nykuto</h1><p>'+text+'</p><script>print()<\/script></body></html>');popup.document.close();});
    document.getElementById('logoutButton').addEventListener('click',function(){sessionStorage.removeItem(tokenKey);location.reload();});
  }
  function init(){
    var classHome='/turma/'+encodeURIComponent(classSlug);document.getElementById('manageClassHome').href=classHome;document.getElementById('manageBackLink').href=classHome;document.getElementById('manageClassLabel').textContent='Gestión · '+classSlug.toUpperCase();document.getElementById('authClassSlug').textContent=classSlug.toUpperCase();document.getElementById('inviteLabel').value='Editor '+classSlug.toUpperCase();
    bindTabs();['taskForm','noticeForm','activityForm','groupForm','fileForm','dateForm','subjectForm'].forEach(function(id){bindForm(id,true);});
    document.getElementById('classForm').addEventListener('submit',function(event){event.preventDefault();var form=event.currentTarget,data=formData(form),wasEditing=form.dataset.editing==='true';if(data.status==='archived'&&form.dataset.originalStatus!=='archived'&&!confirm('¿Archivar esta turma? Su espacio dejará de estar disponible, pero sus datos se conservarán.'))return;mutate(data).then(function(result){if(!result||!result.class)return;var info=result.class,output=document.getElementById('classOutput');output.hidden=false;output.replaceChildren(document.createTextNode((wasEditing?'Turma actualizada: ':'Turma creada: ')+info.name+'. '));if(info.status==='active'){var manage=el('a','','Configurar ahora');manage.href='/gestion/'+encodeURIComponent(info.slug);output.appendChild(manage);}else output.appendChild(document.createTextNode('Está archivada; reactívala desde la lista para configurarla.'));form.reset();clearEditMode(form);});});
    document.getElementById('inviteForm').addEventListener('submit',function(event){event.preventDefault();var data=formData(event.currentTarget);mutate(data).then(function(result){if(!result||!result.inviteToken)return;var output=document.getElementById('inviteOutput'),heading=el('strong','','Invitación creada · se muestra una sola vez'),token=el('code','invite-token',result.inviteToken),expiry=el('small','invite-expiry','Vence: '+result.expiresAt),copy=el('button','','Copiar invitación');copy.type='button';copy.addEventListener('click',function(){copyText(result.inviteToken).then(function(){copy.textContent='Invitación copiada';status('Token de invitación copiado.');}).catch(function(){status('No se pudo copiar automáticamente. Selecciona el token y cópialo manualmente.',true);});});output.hidden=false;output.replaceChildren(heading,token,expiry,copy);});});
    bindActions();
    document.getElementById('tokenForm').addEventListener('submit',function(event){event.preventDefault();accessToken=document.getElementById('accessToken').value.trim();sessionStorage.setItem(tokenKey,accessToken);load();});
    document.getElementById('claimForm').addEventListener('submit',function(event){event.preventDefault();authStatus('Activando…');post({action:'invite.claim',inviteToken:document.getElementById('inviteToken').value.trim(),name:document.getElementById('inviteName').value.trim()},false).then(function(data){accessToken=data.editorToken;sessionStorage.setItem(tokenKey,accessToken);return load();}).catch(function(error){authStatus(error.message,true);});});
    accessToken=sessionStorage.getItem(tokenKey)||'';if(accessToken)load().catch(function(){});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
